"use client";
import { useEffect, useMemo, useState } from "react";
import { BookMarked, Pencil, Plus, Trash2, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createLearningPath, deleteLearningPath, getLearningPaths, getStudents, updateLearningPath } from "../../lib/data";
import { supabase } from "../../lib/supabase";

type Path={id:string;student_id:string;title:string|null;stage_name:string|null;progress_percent:number;status:string;started_on:string|null;completed_on:string|null;notes:string|null;students?:{full_name:string}|null;subjects?:{name_ar:string}|null;curricula?:{name:string}|null};
type Student={id:string;full_name:string}; type Subject={id:string;name_ar:string}; type Curriculum={id:string;name:string};
const PATH_STATUS:[string,string][]=[["active","نشط"],["paused","متوقف"],["completed","مكتمل"]];
export default function LearningPathsPage(){
 const [paths,setPaths]=useState<Path[]>([]),[students,setStudents]=useState<Student[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[curricula,setCurricula]=useState<Curriculum[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Path|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("all");
 async function load(){if(!supabase)return;const [p,s,sub,c]=await Promise.all([getLearningPaths(),getStudents("active"),supabase.from("subjects").select("id,name_ar").eq("is_active",true).order("sort_order"),supabase.from("curricula").select("id,name").order("name")]);if(p.error)setError(p.error.message);else setPaths((p.data||[]) as Path[]);if(s.error)setError(s.error.message);else setStudents((s.data||[]) as Student[]);if(!sub.error)setSubjects((sub.data||[]) as Subject[]);if(!c.error)setCurricula((c.data||[]) as Curriculum[])}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>paths.filter(p=>filter==="all"||p.status===filter),[paths,filter]);
 async function remove(id:string){if(!confirm("حذف هذا المسار؟"))return;const r=await deleteLearningPath(id);if(r.error)setError(r.error.message);else load()}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">التدريس</p><h2>المسارات التعليمية</h2><p className="muted">مسار مستقل لكل طالب حسب المادة والمنهج والمرحلة ونسبة التقدم.</p></div><div className="top-actions"><select className="filter-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل المسارات</option>{PATH_STATUS.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><button className="primary-btn" onClick={()=>{setEditing(null);setError("");setOpen(true)}}><Plus size={17}/> مسار جديد</button></div></section>{visible.length?<div className="student-grid">{visible.map(p=><article className="card" key={p.id}><div className="student-card-head"><div className="avatar"><BookMarked size={17}/></div><div><h3>{p.title||"مسار تعليمي"}</h3><span>{p.students?.full_name||"—"} · {p.subjects?.name_ar||"بدون مادة"}{p.curricula?.name?` · ${p.curricula.name}`:""}</span></div><span className="status">{PATH_STATUS.find(s=>s[0]===p.status)?.[1]||p.status}</span></div><div className="student-meta"><span>{p.stage_name||"بدون مرحلة"}</span><b>{Number(p.progress_percent||0)}%</b></div><div className="meter"><span style={{width:`${Math.min(100,Math.max(0,Number(p.progress_percent||0)))}%`}}/></div><div className="modal-actions"><button className="outline-btn" onClick={()=>{setEditing(p);setOpen(true)}}><Pencil size={14}/> تعديل</button><button className="outline-btn" onClick={()=>remove(p.id)}><Trash2 size={14}/> حذف</button></div></article>)}</div>:<div className="empty card"><BookMarked size={28}/><h2>لا توجد مسارات</h2><p>أضف مسارًا للطالب مع تحديد المادة والمرحلة ونسبة التقدم.</p></div>}{open&&<PathModal path={editing} students={students} subjects={subjects} curricula={curricula} close={()=>{setOpen(false);setEditing(null)}} onSaved={()=>{setOpen(false);setEditing(null);load()}} error={error} setError={setError}/>}</AppShell>
}
function PathModal({path,students,subjects,curricula,close,onSaved,error,setError}:{path:Path|null;students:Student[];subjects:Subject[];curricula:Curriculum[];close:()=>void;onSaved:()=>void;error:string;setError:(v:string)=>void}){const [saving,setSaving]=useState(false);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const progress=Math.min(100,Math.max(0,Number(f.get("progress")||0)));const payload={student_id:String(f.get("student")),subject_id:String(f.get("subject")||"")||null,curriculum_id:String(f.get("curriculum")||"")||null,title:String(f.get("title")||"")||null,stage_name:String(f.get("stage")||"")||null,progress_percent:progress,status:String(f.get("status")),started_on:String(f.get("started_on")||"")||null,completed_on:String(f.get("completed_on")||"")||null,notes:String(f.get("notes")||"")||null};const r=path?await updateLearningPath(path.id,payload):await createLearningPath(payload);if(r.error)setError(r.error.message);else onSaved();setSaving(false)}return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{path?"تعديل المسار":"مسار جديد"}</p><h3>{path?.title||"إضافة مسار تعليمي"}</h3></div><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={save}><div className="form-grid"><Select name="student" label="الطالب" options={students.map(s=>[s.id,s.full_name] as [string,string])} value={path?.student_id}/><Select name="subject" label="المادة" options={subjects.map(s=>[s.id,s.name_ar] as [string,string])} optional value={path?.subjects?subjects.find(s=>s.name_ar===path.subjects?.name_ar)?.id:""}/><Select name="curriculum" label="المنهج" options={curricula.map(c=>[c.id,c.name] as [string,string])} optional value={path?.curricula?curricula.find(c=>c.name===path.curricula?.name)?.id:""}/><Field name="title" label="اسم المسار" defaultValue={path?.title||""} required/><Field name="stage" label="المرحلة" defaultValue={path?.stage_name||""}/><Field name="progress" label="نسبة التقدم" type="number" min="0" max="100" defaultValue={path?.progress_percent??0}/><label className="field"><span>الحالة</span><select name="status" defaultValue={path?.status||"active"}>{PATH_STATUS.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><Field name="started_on" label="تاريخ البدء" type="date" defaultValue={path?.started_on||""}/><Field name="completed_on" label="تاريخ الإكمال" type="date" defaultValue={path?.completed_on||""}/></div><Field name="notes" label="ملاحظات" defaultValue={path?.notes||""}/>{error&&<p className="login-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":path?"حفظ التعديلات":"حفظ المسار"}</button></div></form></div></div>}
function Select({name,label,options,optional=false,value}:{name:string;label:string;options:[string,string][];optional?:boolean;value?:string}){return <label className="field"><span>{label}</span><select name={name} required={!optional} defaultValue={value||""}><option value="">{optional?"بدون اختيار":"اختر"}</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Field({name,label,placeholder,type="text",required=false,defaultValue,min,max}:{name:string;label:string;placeholder?:string;type?:string;required?:boolean;defaultValue?:string|number;min?:string;max?:string}){return <label className="field"><span>{label}</span><input name={name} placeholder={placeholder} type={type} required={required} defaultValue={defaultValue} min={min} max={max}/></label>}
