"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, FileText, Globe2, Pencil, UserRound } from "lucide-react";
import AppShell from "../../../components/app-shell";
import { getStudent, getEvents, getQuranProgress, getExams, getLearningPaths } from "../../../lib/data";
import { countryName } from "../../../lib/countries";
import { formatInTimeZone, formatTimeInZone } from "../../../lib/timezone";

type Props={params:Promise<{id:string}>};
export default function StudentProfilePage({params}:Props){
 const [id,setId]=useState(""),[student,setStudent]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[quran,setQuran]=useState<any[]>([]),[exams,setExams]=useState<any[]>([]),[paths,setPaths]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{params.then(x=>setId(x.id))},[params]);
 useEffect(()=>{if(!id)return;(async()=>{setLoading(true);const s=await getStudent(id);if(s.error){setError(s.error.message);setLoading(false);return}const now=new Date(),to=new Date(now);to.setDate(to.getDate()+60);const [e,q,x,p]=await Promise.all([getEvents(now.toISOString(),to.toISOString()),getQuranProgress(id),getExams(id),getLearningPaths()]);setStudent(s.data);setEvents((e.data||[]).filter((r:any)=>r.student_id===id).slice(0,8));setQuran((q.data||[]).slice(0,8));setExams(x.data||[]);setPaths((p.data||[]).filter((r:any)=>r.student_id===id));setLoading(false)})()},[id]);
 if(loading)return <AppShell><div className="empty card"><UserRound size={28}/><h2>جاري تحميل ملف الطالب…</h2></div></AppShell>;
 if(!student)return <AppShell><div className="empty card"><h2>تعذر العثور على الطالب</h2><p>{error}</p></div></AppShell>;
 return <AppShell><section className="page-actions"><div><Link className="back-link" href="/students"><ArrowRight size={15}/> العودة إلى الطلاب</Link><h2>{student.full_name}</h2><p className="muted">الملف الكامل للطالب ومتابعته التعليمية.</p></div><button className="outline-btn"><Pencil size={15}/> تعديل الملف</button></section><section className="profile-grid"><div className="card profile-summary"><div className="profile-avatar">{student.full_name[0]}</div><h3>{student.full_name}</h3><span className="status">{student.status}</span><div className="profile-facts"><Fact label="العمر" value={student.age?`${student.age} سنة`:"—"}/><Fact label="الدولة" value={countryName(student.country_code)}/><Fact label="التوقيت" value={student.timezone}/><Fact label="اللغة" value={student.native_language||"—"}/><Fact label="الساعات الشهرية" value={`${Number(student.monthly_hours||0)} ساعة`}/><Fact label="ولي الأمر" value={student.contact_name||"—"}/></div></div><div className="profile-main"><div className="card"><div className="section-title"><b><CalendarDays size={16}/> الحصص القادمة</b><Link href="/calendar">التقويم</Link></div>{events.length?events.map(e=><div className="list-row" key={e.id}><div><b>{e.title}</b><span>{formatInTimeZone(e.starts_at,e.timezone)}</span></div><span>{formatTimeInZone(e.starts_at,e.timezone)}</span></div>):<p className="muted">لا توجد حصص قادمة.</p>}</div><div className="card"><div className="section-title"><b><BookOpen size={16}/> القرآن</b><Link href="/quran">متابعة القرآن</Link></div>{quran.length?quran.map(r=><div className="list-row" key={r.id}><div><b>{r.progress_type==="memorization"?"حفظ":"مراجعة"} — سورة {r.surah_number}</b><span>{r.from_ayah||"—"} إلى {r.to_ayah||"—"} · {r.status}</span></div><span>{r.mastery_rating?`${r.mastery_rating}/5`:"—"}</span></div>):<p className="muted">لا توجد سجلات بعد.</p>}</div><div className="card"><div className="section-title"><b><FileText size={16}/> المسارات التعليمية</b><Link href="/learning-paths">المسارات</Link></div>{paths.length?paths.map(p=><div className="list-row" key={p.id}><div><b>{p.title||"مسار"}</b><span>{p.subjects?.name_ar||"بدون مادة"} · {p.stage_name||"—"}</span></div><span>{p.progress_percent}%</span></div>):<p className="muted">لا توجد مسارات تعليمية.</p>}</div><div className="card"><div className="section-title"><b><ClipboardCheck size={16}/> الاختبارات</b><Link href="/exams">الاختبارات</Link></div>{exams.length?exams.map(x=><div className="list-row" key={x.id}><div><b>{x.title}</b><span>{x.exam_type} · {x.scheduled_at?formatInTimeZone(x.scheduled_at,student.timezone):"بدون موعد"}</span></div><span>{x.score!=null&&x.max_score!=null?`${x.score}/${x.max_score}`:x.result||"—"}</span></div>):<p className="muted">لا توجد اختبارات.</p>}</div></div></section></AppShell>;
}
function Fact({label,value}:{label:string;value:string}){return <div className="fact"><span>{label}</span><b>{value}</b></div>}
