"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, Globe2, Pencil, Plus, Repeat2, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createEvent, deleteEvent, getEvents, getStudents, hasEventConflict, updateEvent } from "../../lib/data";
import { formatInTimeZone, formatTimeInZone, zonedDateTimeToUtc } from "../../lib/timezone";
import { cancelRecurringSchedule, createRecurringSchedule, syncRecurringSchedules, updateRecurringSchedule } from "../../lib/recurring";

type Student={id:string;full_name:string;timezone:string};
type Event={id:string;student_id:string|null;event_type:string;title:string;starts_at:string;ends_at:string;timezone:string;status:string;is_makeup:boolean;original_event_id:string|null;recurring_schedule_id:string|null;notes:string|null;students?:{full_name:string}|null};
const STATUSES:[string,string][]=[["scheduled","مجدولة"],["completed","مكتملة"],["cancelled","ملغاة"],["pending_makeup","تحتاج تعويض"]];

export default function CalendarPage(){
 const [students,setStudents]=useState<Student[]>([]),[events,setEvents]=useState<Event[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Event|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("all");
 async function load(){setLoading(true);try{const sr=await syncRecurringSchedules(90);if(sr.error)setError(sr.error.message);const d=new Date();d.setHours(0,0,0,0);const to=new Date(d);to.setDate(to.getDate()+45);const [s,e]=await Promise.all([getStudents(),getEvents(d.toISOString(),to.toISOString())]);if(s.error)setError(s.error.message);else setStudents((s.data||[]) as Student[]);if(e.error)setError(e.error.message);else setEvents((e.data||[]) as Event[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>events.filter(e=>filter==="all"||e.status===filter),[events,filter]);
 async function remove(e:Event){if(!confirm(e.recurring_schedule_id?"حذف هذه الحصة فقط؟ سيستمر الموعد الأسبوعي في الأسابيع التالية.":"حذف هذا الموعد؟"))return;const r=await deleteEvent(e.id);if(r.error)setError(r.error.message);else load()}
 async function status(id:string,status:string){const r=await updateEvent(id,{status});if(r.error)setError(r.error.message);else load()}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">الحصص والمواعيد</p><h2>التقويم</h2><p className="muted">عرض المواعيد القادمة مع توقيت الطالب الفعلي ومنع التعارضات.</p></div><div className="top-actions"><select className="filter-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option>{STATUSES.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><button className="primary-btn" onClick={()=>{setEditing(null);setError("");setOpen(true)}}><Plus size={17}/> إضافة موعد</button></div></section>{loading?<div className="empty card"><CalendarDays size={28}/><h2>جاري تحميل التقويم…</h2></div>:visible.length?<div className="card calendar">{visible.map(e=><article className="calendar-event" key={e.id}><div className="cal-time">{formatTimeInZone(e.starts_at,e.timezone)}</div><div className="cal-line"><span/></div><div className="cal-body"><b>{e.students?.full_name||e.title}</b><span>{e.title} · {formatInTimeZone(e.starts_at,e.timezone)} · {e.timezone}{e.recurring_schedule_id?" · أسبوعي دائم":""}</span></div><span className="pill">{e.is_makeup?"تعويض":e.event_type==="personal"?"شخصي":STATUSES.find(x=>x[0]===e.status)?.[1]||e.status}</span><div className="event-actions"><button className="mini-btn" onClick={()=>{setEditing(e);setError("");setOpen(true)}}><Pencil size={14}/> تعديل</button><button className="mini-btn" onClick={()=>status(e.id,e.status==="completed"?"scheduled":"completed")}><CheckCircle2 size={14}/> {e.status==="completed"?"إعادة جدولة":"تمت"}</button><button className="mini-btn" onClick={()=>remove(e)}><X size={14}/> حذف</button></div></article>)}</div>:<div className="empty card"><CalendarDays size={28}/><h2>لا توجد مواعيد</h2><p>أضف أول حصة وسيتم حفظها بالتوقيت الصحيح للطالب.</p></div>}{open&&<EventModal students={students} event={editing} close={()=>{setOpen(false);setEditing(null)}} onSaved={()=>{setOpen(false);setEditing(null);load()}} error={error} setError={setError}/>}</AppShell>
}

function EventModal({students,event,close,onSaved,error,setError}:{students:Student[];event:Event|null;close:()=>void;onSaved:()=>void;error:string;setError:(x:string)=>void}){
 const initialStudent=event?.student_id||"";const student0=students.find(s=>s.id===initialStudent);const initialZone=event?.timezone||student0?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;const initialDate=event?new Intl.DateTimeFormat("en-CA",{timeZone:event.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(event.starts_at)):new Date().toISOString().slice(0,10);const initialTime=event?formatTimeInZone(event.starts_at,event.timezone,"en-GB"):"18:00";
 const [studentId,setStudentId]=useState(initialStudent),[title,setTitle]=useState(event?.title||"درس قرآن"),[date,setDate]=useState(initialDate),[time,setTime]=useState(initialTime),[duration,setDuration]=useState(event?String(Math.round((new Date(event.ends_at).getTime()-new Date(event.starts_at).getTime())/60000)):"60"),[status,setStatus]=useState(event?.status||"scheduled"),[saving,setSaving]=useState(false),[notes,setNotes]=useState(event?.notes||""),[repeatWeekly,setRepeatWeekly]=useState(Boolean(event?.recurring_schedule_id));
 const student=students.find(s=>s.id===studentId);const timezone=student?.timezone||initialZone;const weekday=new Date(`${date}T12:00:00`).getDay();
 useEffect(()=>{if(student){setTime(prev=>event?prev:prev)}},[student,event]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");try{if(!date||!time)throw new Error("اختر التاريخ والوقت");const minutes=Math.max(15,Number(duration)||60);const baseStart=zonedDateTimeToUtc(date,time,timezone);const end=new Date(baseStart.getTime()+minutes*60000);const payloadBase={student_id:studentId||null,event_type:studentId?(event?.is_makeup?"makeup":"lesson"):"personal",title:title.trim()||"موعد شخصي",timezone,status,is_makeup:event?.is_makeup||false,original_event_id:event?.original_event_id||null,reminder_minutes:30,notes:notes.trim()||null};
 if(event){
   if(!event.recurring_schedule_id&&!repeatWeekly){const conflict=await hasEventConflict(baseStart.toISOString(),end.toISOString(),event.id);if(conflict.error)throw new Error(conflict.error.message);if(conflict.conflict)throw new Error("يوجد تعارض في هذا الموعد.")}
   if(event.recurring_schedule_id&&repeatWeekly){const rr=await updateRecurringSchedule(event.recurring_schedule_id,{student_id:studentId||null,title:payloadBase.title,weekday,start_time:time,duration_minutes:minutes,timezone,notes:notes.trim()||null});if(rr.error)throw new Error(rr.error.message)}
   else if(event.recurring_schedule_id&&!repeatWeekly){const rr=await cancelRecurringSchedule(event.recurring_schedule_id);if(rr.error)throw new Error(rr.error.message)}
   else if(!event.recurring_schedule_id&&repeatWeekly){const rr=await createRecurringSchedule({student_id:studentId||null,title:payloadBase.title,weekday,start_time:time,duration_minutes:minutes,timezone,starts_on:date,notes:notes.trim()||null});if(rr.error)throw new Error(rr.error.message)}
   const r=await updateEvent(event.id,{...payloadBase,starts_at:baseStart.toISOString(),ends_at:end.toISOString()});if(r.error)throw new Error(r.error.message);
 }else{
   const conflict=await hasEventConflict(baseStart.toISOString(),end.toISOString());if(conflict.error)throw new Error(conflict.error.message);if(conflict.conflict)throw new Error("يوجد تعارض في هذا الموعد.");
   if(repeatWeekly){const rr=await createRecurringSchedule({student_id:studentId||null,title:payloadBase.title,weekday,start_time:time,duration_minutes:minutes,timezone,starts_on:date,notes:notes.trim()||null});if(rr.error)throw new Error(rr.error.message);const sr=await syncRecurringSchedules(90);if(sr.error)throw new Error(sr.error.message)}
   else{const r=await createEvent({...payloadBase,starts_at:baseStart.toISOString(),ends_at:end.toISOString()});if(r.error)throw new Error(r.error.message)}
 }
 onSaved();}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ الموعد")}finally{setSaving(false)}}
 return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{event?"تعديل الموعد":"موعد جديد"}</p><h3>{event?"تعديل الحصة":"إضافة موعد"}</h3></div><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={submit}><div className="form-grid"><label className="field"><span>الطالب</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">موعد شخصي</option>{students.map(s=><option value={s.id} key={s.id}>{s.full_name}</option>)}</select></label><label className="field"><span>العنوان</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="درس قرآن" required/></label><label className="field"><span>التاريخ</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label className="field"><span>الوقت</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><label className="field"><span>المدة بالدقائق</span><input type="number" min="15" max="300" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label className="field"><span>حالة الموعد</span><select value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><label className="field"><span>توقيت الموعد</span><div className="readonly-field"><Globe2 size={15}/><input value={timezone} readOnly/></div></label><p className="hint"><Clock3 size={15}/> {student?`الوقت محفوظ وفق توقيت ${student.full_name}: ${timezone}`:"الموعد الشخصي محفوظ وفق توقيت جهازك الحالي."}</p><div className="repeat-box"><label className="checkline"><input type="checkbox" checked={repeatWeekly} onChange={e=>setRepeatWeekly(e.target.checked)}/><Repeat2 size={16}/> تكرار أسبوعي دائم</label>{repeatWeekly&&<p className="hint">سيستمر الموعد كل أسبوع بدون تاريخ انتهاء، حتى تغيّره أو توقف التكرار.</p>}</div><label className="field"><span>ملاحظات</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="login-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":event?"حفظ التعديلات":"حفظ الموعد"}</button></div></form></div></div>
}
