"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, Globe2, Pencil, Plus, Repeat2, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createEvent, deleteEvent, getEvents, getStudents, hasEventConflict, updateEvent } from "../../lib/data";
import { formatTimeInZone, zonedDateTimeToUtc } from "../../lib/timezone";
import { cancelRecurringSchedule, createRecurringSchedule, syncRecurringSchedules, updateRecurringSchedule } from "../../lib/recurring";

type Student={id:string;full_name:string;timezone:string};
type Event={id:string;student_id:string|null;event_type:string;title:string;starts_at:string;ends_at:string;timezone:string;status:string;is_makeup:boolean;original_event_id:string|null;recurring_schedule_id:string|null;notes:string|null;students?:{full_name:string}|null};
const DAYS=[[0,"الأحد"],[1,"الاثنين"],[2,"الثلاثاء"],[3,"الأربعاء"],[4,"الخميس"],[5,"الجمعة"],[6,"السبت"]] as const;
const STATUSES:[string,string][]=[["scheduled","مجدولة"],["completed","مكتملة"],["cancelled","ملغاة"],["pending_makeup","تحتاج تعويض"]];
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const dayLabel=(d:Date)=>new Intl.DateTimeFormat("ar-EG",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d);
export default function CalendarPage(){
 const [students,setStudents]=useState<Student[]>([]),[events,setEvents]=useState<Event[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Event|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[view,setView]=useState<"day"|"week"|"month">("week"),[cursor,setCursor]=useState(new Date());
 async function load(){setLoading(true);try{const sr=await syncRecurringSchedules(90);if(sr.error)setError(sr.error.message);const from=new Date();from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+90);const [s,e]=await Promise.all([getStudents(),getEvents(from.toISOString(),to.toISOString())]);if(s.error)setError(s.error.message);else setStudents((s.data||[]) as Student[]);if(e.error)setError(e.error.message);else setEvents((e.data||[]) as Event[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const range=useMemo(()=>{const d=new Date(cursor);d.setHours(0,0,0,0);if(view==="day")return {from:d,to:new Date(d.getTime()+86400000)};if(view==="week"){const from=new Date(d);from.setDate(d.getDate()-d.getDay());return {from,to:new Date(from.getTime()+7*86400000)}}return {from:new Date(d.getFullYear(),d.getMonth(),1),to:new Date(d.getFullYear(),d.getMonth()+1,1)}},[cursor,view]);
 const visible=useMemo(()=>events.filter(e=>{const t=new Date(e.starts_at);return t>=range.from&&t<range.to&&(filter==="all"||e.status===filter)}).sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)),[events,range,filter]);
 const groups=useMemo(()=>{const m=new Map<string,Event[]>();visible.forEach(e=>{const k=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:e.timezone}).format(new Date(e.starts_at));if(!m.has(k))m.set(k,[]);m.get(k)!.push(e)});return [...m.entries()]},[visible]);
 const title=view==="day"?dayLabel(cursor):view==="week"?`الأسبوع · ${new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"long"}).format(range.from)} – ${new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"long"}).format(new Date(range.to.getTime()-86400000))}`:new Intl.DateTimeFormat("ar-EG",{month:"long",year:"numeric"}).format(cursor);
 function shift(n:number){const d=new Date(cursor);if(view==="day")d.setDate(d.getDate()+n);else if(view==="week")d.setDate(d.getDate()+7*n);else d.setMonth(d.getMonth()+n);setCursor(d)}
 async function remove(e:Event){if(!confirm(e.recurring_schedule_id?"حذف هذه الحصة فقط؟ سيستمر الموعد الأسبوعي.":"حذف هذا الموعد؟"))return;const r=await deleteEvent(e.id);if(r.error)setError(r.error.message);else load()}
 async function toggleStatus(e:Event){const r=await updateEvent(e.id,{status:e.status==="completed"?"scheduled":"completed"});if(r.error)setError(r.error.message);else load()}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">الحصص والمواعيد</p><h2>التقويم</h2><p className="muted">حصص اليوم والأسبوع والشهر في واجهة واحدة واضحة.</p></div><div className="top-actions"><select className="filter-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option>{STATUSES.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><button className="primary-btn" onClick={()=>{setEditing(null);setError("");setOpen(true)}}><Plus size={17}/> إضافة موعد</button></div></section>
 <div className="calendar-toolbar card"><div className="calendar-tabs"><button className={view==="day"?"active":""} onClick={()=>setView("day")}>اليوم</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>الأسبوع</button><button className={view==="month"?"active":""} onClick={()=>setView("month")}>الشهر</button></div><div className="calendar-nav"><button className="outline-btn" onClick={()=>setCursor(new Date())}>اليوم</button><button className="icon-btn" onClick={()=>shift(-1)}>‹</button><strong>{title}</strong><button className="icon-btn" onClick={()=>shift(1)}>›</button></div></div>
 {loading?<div className="empty card"><CalendarDays size={28}/><h2>جاري تحميل التقويم…</h2></div>:groups.length?<div className="calendar-groups">{groups.map(([date,list])=><section className="card calendar-day" key={date}><header className="calendar-day-head"><div><span>{dayLabel(new Date(`${date}T12:00:00`))}</span><b>{list.length} {list.length===1?"حصة":"حصص"}</b></div><span className="day-count">{list.filter(e=>e.status==="completed").length} مكتملة</span></header><div className="calendar-list">{list.map(e=><article className="calendar-event" key={e.id}><div className="cal-time"><b>{formatTimeInZone(e.starts_at,e.timezone)}</b><small>{Math.round((+new Date(e.ends_at)-+new Date(e.starts_at))/60000)} د</small></div><div className="cal-line"><span/></div><div className="cal-body"><b>{e.students?.full_name||e.title}</b><span>{e.title} · {e.recurring_schedule_id?"أسبوعي دائم":"مرة واحدة"}</span><small><Globe2 size={13}/> {e.timezone} · توقيتك {formatTimeInZone(e.starts_at,Intl.DateTimeFormat().resolvedOptions().timeZone)}</small></div><span className="pill">{e.is_makeup?"تعويض":e.event_type==="personal"?"شخصي":STATUSES.find(x=>x[0]===e.status)?.[1]||e.status}</span><div className="event-actions"><button className="mini-btn" onClick={()=>{setEditing(e);setError("");setOpen(true)}}><Pencil size={14}/> تعديل</button><button className="mini-btn" onClick={()=>toggleStatus(e)}><CheckCircle2 size={14}/> {e.status==="completed"?"إعادة":"تمت"}</button><button className="mini-btn" onClick={()=>remove(e)}><X size={14}/> حذف</button></div></article>)}</div></section>)}</div>:<div className="empty card"><CalendarDays size={28}/><h2>لا توجد حصص</h2><p>لا توجد مواعيد في نطاق العرض الحالي.</p></div>}
 {open&&<EventModal students={students} event={editing} close={()=>{setOpen(false);setEditing(null)}} onSaved={()=>{setOpen(false);setEditing(null);load()}} error={error} setError={setError}/>}</AppShell>;
}
function EventModal({students,event,close,onSaved,error,setError}:{students:Student[];event:Event|null;close:()=>void;onSaved:()=>void;error:string;setError:(x:string)=>void}){
 const student0=students.find(s=>s.id===event?.student_id),zone=event?.timezone||student0?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;const [studentId,setStudentId]=useState(event?.student_id||""),[title,setTitle]=useState(event?.title||"درس قرآن"),[date,setDate]=useState(event?new Intl.DateTimeFormat("en-CA",{timeZone:zone}).format(new Date(event.starts_at)):dateKey(new Date())),[time,setTime]=useState(event?formatTimeInZone(event.starts_at,zone,"en-GB"):"18:00"),[duration,setDuration]=useState(event?String(Math.round((+new Date(event.ends_at)-+new Date(event.starts_at))/60000)):"60"),[repeat,setRepeat]=useState(Boolean(event?.recurring_schedule_id)),[weekday,setWeekday]=useState(event?new Date(`${date}T12:00:00`).getDay():new Date().getDay()),[status,setStatus]=useState(event?.status||"scheduled"),[notes,setNotes]=useState(event?.notes||""),[saving,setSaving]=useState(false);const student=students.find(s=>s.id===studentId),tz=student?.timezone||zone,local=student?formatTimeInZone(zonedDateTimeToUtc(date,time,tz),Intl.DateTimeFormat().resolvedOptions().timeZone):time;
 async function submit(ev:React.FormEvent){ev.preventDefault();setSaving(true);setError("");try{if(!time||(!repeat&&!date))throw new Error("أكمل بيانات الموعد");const minutes=Math.max(15,Number(duration)||60),start=zonedDateTimeToUtc(date,time,tz),end=new Date(start.getTime()+minutes*60000),payload={student_id:studentId||null,event_type:studentId?(event?.is_makeup?"makeup":"lesson"):"personal",title:title.trim()||"موعد شخصي",timezone:tz,status,is_makeup:event?.is_makeup||false,original_event_id:event?.original_event_id||null,reminder_minutes:30,notes:notes.trim()||null};if(event){if(event.recurring_schedule_id&&repeat){const r=await updateRecurringSchedule(event.recurring_schedule_id,{student_id:studentId||null,title:payload.title,weekday,start_time:time,duration_minutes:minutes,timezone:tz,notes:notes.trim()||null});if(r.error)throw new Error(r.error.message)}else if(event.recurring_schedule_id&&!repeat){const r=await cancelRecurringSchedule(event.recurring_schedule_id);if(r.error)throw new Error(r.error.message)}else if(!event.recurring_schedule_id&&repeat){const r=await createRecurringSchedule({student_id:studentId||null,title:payload.title,weekday,start_time:time,duration_minutes:minutes,timezone:tz,starts_on:date,notes:notes.trim()||null});if(r.error)throw new Error(r.error.message)}else{const c=await hasEventConflict(start.toISOString(),end.toISOString(),event.id);if(c.error)throw new Error(c.error.message);if(c.conflict)throw new Error("يوجد تعارض في هذا الموعد.")}const r=await updateEvent(event.id,{...payload,starts_at:start.toISOString(),ends_at:end.toISOString()});if(r.error)throw new Error(r.error.message)}else if(repeat){const r=await createRecurringSchedule({student_id:studentId||null,title:payload.title,weekday,start_time:time,duration_minutes:minutes,timezone:tz,starts_on:date,notes:notes.trim()||null});if(r.error)throw new Error(r.error.message);const s=await syncRecurringSchedules(90);if(s.error)throw new Error(s.error.message)}else{const c=await hasEventConflict(start.toISOString(),end.toISOString());if(c.error)throw new Error(c.error.message);if(c.conflict)throw new Error("يوجد تعارض في هذا الموعد.");const r=await createEvent({...payload,starts_at:start.toISOString(),ends_at:end.toISOString()});if(r.error)throw new Error(r.error.message)}onSaved()}catch(x){setError(x instanceof Error?x.message:"تعذر حفظ الموعد")}finally{setSaving(false)}}
 return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{event?"تعديل الموعد":"موعد جديد"}</p><h3>{event?"تعديل الحصة":"إضافة موعد"}</h3></div><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={submit}><div className="form-grid"><label className="field"><span>الطالب</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">موعد شخصي</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label className="field"><span>العنوان</span><input value={title} onChange={e=>setTitle(e.target.value)} required/></label></div><div className="repeat-box"><span className="field-label">نوع الموعد</span><label className="checkline"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/><Repeat2 size={16}/> تكرار أسبوعي دائم</label><p className="hint">{repeat?"اختر يوم الأسبوع والوقت وسيستمر الموعد كل أسبوع.":"موعد لمرة واحدة بتاريخ ووقت محددين."}</p></div><div className="form-grid">{repeat?<label className="field"><span>يوم الأسبوع</span><select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>:<label className="field"><span>التاريخ</span><input type="date" value={date} onChange={e=>{setDate(e.target.value);setWeekday(new Date(`${e.target.value}T12:00:00`).getDay())}} required/></label>}<label className="field"><span>الوقت بتوقيت الطالب</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label></div><label className="field"><span>توقيت الطالب</span><div className="readonly-field"><Globe2 size={15}/><input value={tz} readOnly/></div></label><div className="field"><span>الوقت بتوقيتك المحلي</span><div className="readonly-field"><Clock3 size={15}/><input value={student?local:time} readOnly/></div></div><label className="field"><span>مدة الحصة بالدقائق</span><input type="number" min="15" max="300" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label className="field"><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className="field"><span>ملاحظات</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="login-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الموعد"}</button></div></form></div></div>;
}