"use client";
import { useEffect, useState } from "react";
import { CalendarDays, Clock3, Globe2, Plus, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createEvent, getEvents, getStudents, hasEventConflict } from "../../lib/data";

type Student={id:string;full_name:string;timezone:string};
type Event={id:string;student_id:string|null;event_type:string;title:string;starts_at:string;ends_at:string;timezone:string;status:string;is_makeup:boolean;students?:{full_name:string}|null};
export default function CalendarPage(){const [students,setStudents]=useState<Student[]>([]),[events,setEvents]=useState<Event[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");async function load(){setLoading(true);const d=new Date();const to=new Date(d);to.setDate(to.getDate()+30);const [s,e]=await Promise.all([getStudents(),getEvents(d.toISOString(),to.toISOString())]);if(!s.error)setStudents((s.data||[]) as Student[]);if(!e.error)setEvents((e.data||[]) as Event[]);setLoading(false)}useEffect(()=>{load()},[]);
 return <AppShell><section className="page-actions"><div><p className="eyebrow">30 يومًا قادمة</p><h2>التقويم والحصص</h2></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> إضافة موعد</button></section>{loading?<div className="empty card"><h2>جاري تحميل التقويم…</h2></div>:<div className="card calendar">{events.length?events.map(e=><div className="calendar-event" key={e.id}><div className="cal-time">{new Date(e.starts_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</div><div className="cal-line"><span/></div><div className="cal-body"><b>{e.students?.full_name||e.title}</b><span>{e.title} · {new Date(e.starts_at).toLocaleDateString("ar-EG")} · {e.timezone}</span></div><span className="pill">{e.is_makeup?"تعويض":e.event_type==="personal"?"شخصي":"حصة"}</span></div>):<div className="empty"><CalendarDays size={22}/><h2>لا توجد مواعيد</h2></div>}</div>}{open&&<EventModal students={students} close={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}} error={error} setError={setError}/>}</AppShell>}
function EventModal({students,close,onSaved,error,setError}:{students:Student[];close:()=>void;onSaved:()=>void;error:string;setError:(x:string)=>void}){const [studentId,setStudentId]=useState(""),[saving,setSaving]=useState(false);const student=students.find(s=>s.id===studentId);const timezone=student?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const date=String(f.get("date")),time=String(f.get("time"));const start=new Date(`${date}T${time}:00`),duration=Number(f.get("duration")||60),end=new Date(start.getTime()+duration*60000);const conflict=await hasEventConflict(start.toISOString(),end.toISOString());if(conflict.error||conflict.conflict){setError(conflict.error?.message||"الموعد يتعارض مع موعد موجود");setSaving(false);return}const r=await createEvent({student_id:studentId||null,event_type:studentId?"lesson":"personal",title:String(f.get("title")),starts_at:start.toISOString(),ends_at:end.toISOString(),timezone,status:"scheduled",is_makeup:false,reminder_minutes:30,notes:String(f.get("notes")||"")||null});if(r.error)setError(r.error.message);else onSaved();setSaving(false)}return <div className="overlay"><div className="modal"><div className="modal-head"><h3>إضافة موعد</h3><button className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={submit}><div className="form-grid"><label className="field"><span>الطالب</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">موعد شخصي</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><Field name="title" label="العنوان" required/><Field name="date" label="التاريخ" type="date" required/><Field name="time" label="الوقت" type="time" required/><Field name="duration" label="المدة بالدقائق" type="number" placeholder="60"/><label className="field"><span>توقيت الموعد</span><div className="readonly-field"><Globe2 size={15}/><input value={timezone} readOnly/></div></label></div><Field name="notes" label="ملاحظات"/><p className="hint"><Clock3 size={15}/> {student?`تم اختيار توقيت ${student.full_name} تلقائيًا: ${timezone}`:"اختر الطالب لتحديد التوقيت تلقائيًا."}</p>{error&&<p className="hint">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الموعد"}</button></div></form></div></div>}
function Field({name,label,placeholder,type="text",required=false}:{name:string;label:string;placeholder?:string;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><input name={name} type={type} placeholder={placeholder} required={required}/></label>}
