"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Copy, FileText, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { supabase } from "../../lib/supabase";
import { requireTeacherId, getCurrentTeacherId } from "../../lib/current-teacher";

type StudentRel={full_name:string};
type Event={id:string;title:string;starts_at:string;students?:StudentRel|StudentRel[]|null};
type Report={id:string;event_id:string;taught_text:string|null;review_text:string|null;homework_text:string|null;next_lesson_plan:string|null;private_notes:string|null;teacher_rating:number|null;events?:{title:string;starts_at:string;students?:StudentRel|StudentRel[]|null}|null};
const one=(v:StudentRel|StudentRel[]|null|undefined)=>Array.isArray(v)?v[0]||null:v;
export default function ReportsPage(){const [rows,setRows]=useState<Report[]>([]),[events,setEvents]=useState<Event[]>([]),[open,setOpen]=useState(false),[selected,setSelected]=useState<Report|null>(null),[lang,setLang]=useState<"ar"|"fr"|"en">("ar"),[saving,setSaving]=useState(false),[error,setError]=useState("");async function load(){if(!supabase)return;const t=await requireTeacherId();const [r,e]=await Promise.all([supabase.from("lesson_reports").select("*,events(title,starts_at,students(full_name))").eq("teacher_id",t).order("created_at",{ascending:false}),supabase.from("events").select("id,title,starts_at,students(full_name)").eq("teacher_id",t).eq("event_type","lesson").order("starts_at",{ascending:false}).limit(100)]);if(!r.error)setRows((r.data||[]) as Report[]);if(!e.error)setEvents((e.data||[]) as Event[])}useEffect(()=>{load()},[]);const reportEventIds=useMemo(()=>new Set(rows.map(r=>r.event_id)),[rows]);const missing=events.filter(e=>!reportEventIds.has(e.id));function edit(r:Report){setSelected(r);setLang("ar");setOpen(true)}async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setSaving(true);setError("");const f=new FormData(e.currentTarget),t=await requireTeacherId();const r=await supabase.from("lesson_reports").upsert({id:selected?.id||undefined,event_id:String(f.get("event")),taught_text:String(f.get("taught")||"")||null,review_text:String(f.get("review")||"")||null,homework_text:String(f.get("homework")||"")||null,next_lesson_plan:String(f.get("next")||"")||null,private_notes:String(f.get("private")||"")||null,teacher_rating:Number(f.get("rating"))||null,teacher_id:t},{onConflict:"event_id"}).select().single();if(r.error)setError(r.error.message);else{setOpen(false);setSelected(null);load()}setSaving(false)}function parentCopy(r:Report){const student=one(r.events?.students)?.full_name||"الطالب";if(lang==="ar")return `السلام عليكم،\n\nملخص حصة ${student}:\n\nما تم تدريسه:\n${r.taught_text||"—"}\n\nالمراجعة:\n${r.review_text||"—"}\n\nالواجب:\n${r.homework_text||"—"}\n\nالحصة القادمة:\n${r.next_lesson_plan||"—"}`;if(lang==="fr")return `Bonjour,\n\nCompte rendu du cours de ${student} :\n\nCours d’aujourd’hui :\n${r.taught_text||"—"}\n\nRévision :\n${r.review_text||"—"}\n\nDevoir :\n${r.homework_text||"—"}\n\nProchain cours :\n${r.next_lesson_plan||"—"}`;return `Hello,\n\nLesson summary for ${student}:\n\nToday’s lesson:\n${r.taught_text||"—"}\n\nRevision:\n${r.review_text||"—"}\n\nHomework:\n${r.homework_text||"—"}\n\nNext lesson:\n${r.next_lesson_plan||"—"}`}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">التدريس</p><h2>تقارير الحصص</h2><p className="muted">تقرير كامل للحصة، مع نسخة جاهزة للإرسال لولي الأمر.</p></div></section><div className="grid4"><div className="card stat"><div className="stat-label">التقارير المسجلة</div><div className="stat-value">{rows.length}</div></div><div className="card stat"><div className="stat-label">حصص بلا تقرير</div><div className="stat-value">{missing.length}</div></div><div className="card stat"><div className="stat-label">آخر تحديث</div><div className="stat-value">{rows[0]?new Date(rows[0].created_at||Date.now()).toLocaleDateString("ar-EG"):"—"}</div></div><div className="card stat"><div className="stat-label">لغة النسخة</div><div className="stat-value">{lang.toUpperCase()}</div></div></div><div className="card calendar">{rows.length?rows.map(r=><div className="calendar-event" key={r.id}><div className="avatar"><FileText size={17}/></div><div className="cal-body"><b>{one(r.events?.students)?.full_name||"—"}</b><span>{r.events?.title||"حصة"} · {r.events?.starts_at?new Date(r.events.starts_at).toLocaleString("ar-EG"):"—"}</span></div><button className="outline-btn" onClick={()=>edit(r)}>فتح التقرير</button><button className="mini-btn" onClick={()=>navigator.clipboard?.writeText(parentCopy(r))}><Copy size={14}/> نسخ لولي الأمر</button></div>):<div className="empty"><FileText size={24}/><h2>لا توجد تقارير</h2><p>يمكنك إنشاء تقرير للحصة من هنا.</p></div>}</div>{missing.length>0&&<div className="card"><div className="section-title"><b>حصص تحتاج تقريرًا</b></div>{missing.slice(0,10).map(e=><div className="list-row" key={e.id}><div><b>{one(e.students)?.full_name||"—"}</b><span>{e.title} · {new Date(e.starts_at).toLocaleString("ar-EG")}</span></div><button className="outline-btn" onClick={()=>{setSelected({id:"",event_id:e.id,taught_text:null,review_text:null,homework_text:null,next_lesson_plan:null,private_notes:null,teacher_rating:null,events:e as any});setOpen(true)}}>إنشاء التقرير</button></div>)}</div>}
 {open&&<div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">التدريس</p><h3>تقرير الحصة</h3></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={18}/></button></div><form className="form" onSubmit={save}><SelectEvent events={events} selected={selected?.event_id}/><Field name="taught" label="ما تم تدريسه اليوم" defaultValue={selected?.taught_text||""}/><Field name="review" label="المراجعة" defaultValue={selected?.review_text||""}/><Field name="homework" label="الواجب" defaultValue={selected?.homework_text||""}/><Field name="next" label="الحصة القادمة" defaultValue={selected?.next_lesson_plan||""}/><Field name="private" label="ملاحظات خاصة" defaultValue={selected?.private_notes||""}/><Field name="rating" label="تقييم المعلم" type="number" defaultValue={selected?.teacher_rating||""}/><div className="language-row"><span>نسخة ولي الأمر:</span>{[["ar","العربية"],["fr","Français"],["en","English"]].map(([v,l])=><button type="button" key={v} className={lang===v?"selected":""} onClick={()=>setLang(v as any)}>{l}</button>)}</div>{selected&&<div className="preview"><div className="preview-head"><b>معاينة</b><button type="button" className="mini-btn" onClick={()=>navigator.clipboard?.writeText(parentCopy(selected))}><Copy size={14}/> نسخ</button></div><pre>{parentCopy(selected)}</pre></div>}<p className="hint">{error||"الحفظ يربط التقرير بالحصة نفسها ويمكن تعديله لاحقًا."}</p><div className="modal-actions"><button type="button" className="outline-btn" onClick={()=>setOpen(false)}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?<span>جارٍ الحفظ…</span>:<><Check size={16}/> حفظ التقرير</>}</button></div></form></div></div>}</AppShell>}
function SelectEvent({events,selected}:{events:Event[];selected?:string}){return <label className="field"><span>الحصة</span><select name="event" defaultValue={selected||""} required><option value="">اختر الحصة</option>{events.map(e=><option key={e.id} value={e.id}>{one(e.students)?.full_name||"—"} — {new Date(e.starts_at).toLocaleString("ar-EG")} — {e.title}</option>)}</select></label>}
function Field({name,label,type="text",defaultValue}:{name:string;label:string;type?:string;defaultValue?:string|number}){return <label className="field"><span>{label}</span>{["taught","review","homework","next","private"].includes(name)?<textarea name={name} defaultValue={defaultValue}/>:<input name={name} type={type} defaultValue={defaultValue}/>}</label>}
