"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { requireTeacherId } from "../lib/current-teacher";

const cx=(...x:(string|false|undefined)[])=>x.filter(Boolean).join(" ");

export function PersonalSchedule(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState({title:"",date:"",start:"",end:"",type:"prep",notes:""});
 const load=async()=>{setLoading(true);const t=await requireTeacherId();const {data}=await supabase!.from("teacher_blocks").select("*").eq("teacher_id",t).order("starts_at");setRows(data||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();const t=await requireTeacherId();const s=new Date(`${form.date}T${form.start}:00`),en=new Date(`${form.date}T${form.end}:00`);const {error}=await supabase!.from("teacher_blocks").insert({teacher_id:t,title:form.title,starts_at:s.toISOString(),ends_at:en.toISOString(),block_type:form.type,notes:form.notes||null});if(error)alert(error.message);else{setForm({title:"",date:"",start:"",end:"",type:"prep",notes:""});load()}}
 async function remove(id:string){await supabase!.from("teacher_blocks").delete().eq("id",id);load()}
 return <section><div className="hero"><div><p className="eyebrow">الإدارة</p><h2>جدولي الشخصي</h2><p>الأوقات التي تمنع الحجز: تحضير، مراجعة، حفظ أو التزام شخصي.</p></div></div><div className="module-grid"><form className="card form" onSubmit={add}><h3>إضافة التزام</h3><div className="form-grid"><label className="field"><span>العنوان</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>النوع</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="prep">تحضير</option><option value="revision">مراجعة</option><option value="personal">شخصي</option><option value="other">أخرى</option></select></label><label className="field"><span>التاريخ</span><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field"><span>من</span><input required type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label className="field"><span>إلى</span><input required type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label></div><label className="field"><span>ملاحظات</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary-btn">حفظ الالتزام</button></form><div className="card"><h3>الالتزامات المسجلة</h3>{loading?<p>جاري التحميل…</p>:rows.length===0?<p className="muted">لا توجد التزامات.</p>:rows.map(r=><div className="list-row" key={r.id}><div><b>{r.title}</b><span>{new Date(r.starts_at).toLocaleString("ar-EG",{dateStyle:"medium",timeStyle:"short"})} — {new Date(r.ends_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</span></div><button className="mini-btn" onClick={()=>remove(r.id)}>حذف</button></div>)}</div></div></section>
}

export function HoursPage(){
 const [rows,setRows]=useState<any[]>([]),[month,setMonth]=useState(new Date().toISOString().slice(0,7));
 useEffect(()=>{(async()=>{const t=await requireTeacherId();const from=`${month}-01T00:00:00.000Z`,d=new Date(`${month}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);const to=d.toISOString();const {data}=await supabase!.from("events").select("student_id,starts_at,ends_at,status,students(full_name)").eq("teacher_id",t).gte("starts_at",from).lt("starts_at",to).eq("event_type","lesson");setRows(data||[])})()},[month]);
 const stats=useMemo(()=>{const m=new Map<string,any>();for(const r of rows){const k=r.student_id||"unknown";const x=m.get(k)||{name:r.students?.full_name||"غير محدد",hours:0,count:0,completed:0};x.count++;if(r.status==="completed")x.completed++;x.hours+=(new Date(r.ends_at).getTime()-new Date(r.starts_at).getTime())/3600000;m.set(k,x)}return [...m.values()]},[rows]);
 const total=stats.reduce((s,x)=>s+x.hours,0),done=stats.reduce((s,x)=>s+x.completed,0);
 return <section><div className="hero"><div><p className="eyebrow">الإدارة</p><h2>الساعات</h2><p>تجميع ساعات الحصص حسب الشهر والطالب، مع فصل المنفذ عن المجدول.</p></div></div><div className="stats grid4"><Stat label="إجمالي الساعات" value={`${total.toFixed(1)} ساعة`}/><Stat label="الحصص" value={rows.length}/><Stat label="المكتملة" value={done}/><Stat label="الشهر" value={month}/></div><div className="card"><div className="page-actions"><h3>ملخص حسب الطالب</h3><input className="month-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>الطالب</th><th>الساعات</th><th>الحصص</th><th>المكتملة</th></tr></thead><tbody>{stats.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.hours.toFixed(1)}</td><td>{x.count}</td><td>{x.completed}</td></tr>)}</tbody></table></div></div></section>
}

export function PaymentsPage(){
 const [rows,setRows]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[form,setForm]=useState({student_id:"",billing_month:new Date().toISOString().slice(0,7),amount_due:"",amount_paid:""});
 async function load(){const t=await requireTeacherId();const [p,s]=await Promise.all([supabase!.from("payments").select("*,students(full_name)").eq("teacher_id",t).order("billing_month",{ascending:false}),supabase!.from("students").select("id,full_name").eq("teacher_id",t).eq("status","active").order("full_name")]);setRows(p.data||[]);setStudents(s.data||[])}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();const t=await requireTeacherId();const {error}=await supabase!.from("payments").insert({teacher_id:t,student_id:form.student_id,billing_month:`${form.billing_month}-01`,amount_due:Number(form.amount_due||0),amount_paid:Number(form.amount_paid||0),paid_at:Number(form.amount_paid||0)>0?new Date().toISOString():null});if(error)alert(error.message);else{setForm({...form,student_id:"",amount_due:"",amount_paid:""});load()}}
 return <section><div className="hero"><div><p className="eyebrow">الإدارة</p><h2>المدفوعات</h2><p>سجل شهري واضح للمستحق والمدفوع والمتبقي لكل طالب.</p></div></div><div className="module-grid"><form className="card form" onSubmit={save}><h3>تسجيل دفعة</h3><label className="field"><span>الطالب</span><select required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">اختر الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><div className="form-grid"><label className="field"><span>الشهر</span><input required type="month" value={form.billing_month} onChange={e=>setForm({...form,billing_month:e.target.value})}/></label><label className="field"><span>المستحق</span><input type="number" min="0" value={form.amount_due} onChange={e=>setForm({...form,amount_due:e.target.value})}/></label><label className="field"><span>المدفوع</span><input type="number" min="0" value={form.amount_paid} onChange={e=>setForm({...form,amount_paid:e.target.value})}/></label></div><button className="primary-btn">حفظ</button></form><div className="card"><h3>السجل</h3>{rows.length===0?<p className="muted">لا توجد مدفوعات.</p>:rows.map(r=><div className="list-row" key={r.id}><div><b>{r.students?.full_name||"—"}</b><span>{new Date(r.billing_month).toLocaleDateString("ar-EG",{year:"numeric",month:"long"})}</span></div><div><b>{Number(r.amount_paid||0).toFixed(2)}</b><span>من {Number(r.amount_due||0).toFixed(2)}</span></div></div>)}</div></div></section>
}

export function NotificationsPage(){
 const [items,setItems]=useState<string[]>([]);
 useEffect(()=>{(async()=>{const t=await requireTeacherId();const now=new Date(),next=new Date(now.getTime()+7*86400000);const [e,h,p]=await Promise.all([supabase!.from("events").select("id,title,starts_at,students(full_name)").eq("teacher_id",t).gte("starts_at",now.toISOString()).lt("starts_at",next.toISOString()).eq("status","scheduled"),supabase!.from("homework").select("id,title,due_date,students(full_name)").eq("teacher_id",t).neq("status","completed"),supabase!.from("payments").select("id,amount_due,amount_paid,students(full_name)").eq("teacher_id",t)]);const out:string[]=[];(e.data||[]).forEach(x=>out.push(`حصة قادمة: ${x.students?.full_name||x.title} — ${new Date(x.starts_at).toLocaleString("ar-EG",{dateStyle:"medium",timeStyle:"short"})}`));(h.data||[]).filter(x=>x.due_date&&new Date(x.due_date)<now).forEach(x=>out.push(`واجب متأخر: ${x.students?.full_name||x.title}`));(p.data||[]).filter(x=>Number(x.amount_due||0)>Number(x.amount_paid||0)).forEach(x=>out.push(`مستحق غير مكتمل: ${x.students?.full_name||"طالب"}`));setItems(out)})()},[]);
 return <section><div className="hero"><div><p className="eyebrow">الإدارة</p><h2>التنبيهات</h2><p>ملخص التنبيهات العملية التي تحتاج انتباهك الآن.</p></div></div><div className="card">{items.length===0?<div className="empty"><h3>لا توجد تنبيهات حرجة.</h3><p className="muted">الوضع الحالي هادئ.</p></div>:items.map((x,i)=><div className="list-row" key={i}><span>{x}</span></div>)}</div></section>
}

export function SettingsPage(){
 const [name,setName]=useState(""),[tz,setTz]=useState("Africa/Cairo"),[locale,setLocale]=useState("ar"),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const t=await requireTeacherId();const {data}=await supabase!.from("profiles").select("full_name,timezone,locale").eq("id",t).single();if(data){setName(data.full_name||"");setTz(data.timezone||"Africa/Cairo");setLocale(data.locale||"ar")}})()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const t=await requireTeacherId();const {error}=await supabase!.from("profiles").update({full_name:name,timezone:tz,locale}).eq("id",t);setSaving(false);if(error)alert(error.message);else alert("تم حفظ الإعدادات")}
 return <section><div className="hero"><div><p className="eyebrow">الإدارة</p><h2>الإعدادات</h2><p>بيانات الأستاذ واللغة والمنطقة الزمنية الافتراضية.</p></div></div><form className="card form settings-form" onSubmit={save}><h3>بيانات الحساب</h3><label className="field"><span>اسم الأستاذ</span><input value={name} onChange={e=>setName(e.target.value)} /></label><label className="field"><span>المنطقة الزمنية</span><input value={tz} onChange={e=>setTz(e.target.value)} placeholder="Africa/Cairo" /></label><label className="field"><span>اللغة</span><select value={locale} onChange={e=>setLocale(e.target.value)}><option value="ar">العربية</option><option value="fr">Français</option><option value="en">English</option></select></label><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الإعدادات"}</button></form></section>
}

function Stat({label,value}:{label:string;value:any}){return <div className="card stat"><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>}
