"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, BookOpen, CalendarDays, CheckCircle2, ChevronDown, ClipboardList, Clock3, CreditCard, FileText, GraduationCap, Plus, Search, Settings2, Trash2, UserRound, X } from "lucide-react";
import "../app/management-pages.css";

type Kind = "hours" | "payments" | "exams" | "paths" | "reports" | "alerts" | "settings" | "my-calendar" | "lessons";
type Row = { id:string; title:string; subtitle:string; status:string; value?:string; date?:string };

const icons = { hours: Clock3, payments: CreditCard, exams: GraduationCap, paths: BookOpen, reports: FileText, alerts: Bell, settings: Settings2, "my-calendar": CalendarDays, lessons: ClipboardList };
const config: Record<Kind,{title:string; subtitle:string; primary:string; tabs:string[]; stats:[string,string][]; seed:Row[]; columns:string[]}> = {
  hours:{title:"متابعة الساعات الشهرية",subtitle:"راقب الساعات المنجزة لكل طالب، وسجّل الحصص والتقدم الشهري.",primary:"تسجيل حصة",tabs:["نظرة عامة","ساعات الطلاب","السجل الشهري"],stats:[["ساعات الفترة","0.0 / 0.0"],["الحصص المنجزة","0"],["المتبقي","0 ساعة"],["إجمالي الطلاب","0"]],columns:["الطالب","الساعات","نسبة الإنجاز","الإجراء"],seed:[{id:"1",title:"فادل",subtitle:"بلجيكا · برنامج القرآن واللغة العربية",status:"نشط",value:"0.0 / 8 ساعات"},{id:"2",title:"هارون",subtitle:"المملكة المتحدة · القرآن",status:"نشط",value:"0.0 / 8 ساعات"},{id:"3",title:"طارق",subtitle:"الإمارات · اللغة العربية",status:"نشط",value:"0.0 / 8 ساعات"}]},
  payments:{title:"المدفوعات",subtitle:"سجّل المدفوعات وتابع حالة الحسابات الشهرية لكل طالب.",primary:"تسجيل دفعة",tabs:["المدفوعات","الحسابات","الملخص"],stats:[["إجمالي المدفوع","0"],["المستحق","0"],["دفعات هذا الشهر","0"],["حسابات معلقة","0"]],columns:["الطالب / الجهة","المبلغ","الحالة","الإجراء"],seed:[{id:"1",title:"مركز الطالب",subtitle:"فاتورة شهرية",status:"معلق",value:"—"},{id:"2",title:"حساب فادل",subtitle:"دفعة شهرية",status:"مكتمل",value:"—"}]},
  exams:{title:"الاختبارات والتقييم",subtitle:"أنشئ الاختبارات، سجّل النتائج، وتابع تطور الطلاب.",primary:"إنشاء اختبار",tabs:["الاختبارات","النتائج","بنك التقييم"],stats:[["اختبارات نشطة","0"],["نتائج مسجلة","0"],["متوسط النجاح","0%"],["بحاجة لمراجعة","0"]],columns:["الاختبار","الطالب","الحالة","الإجراء"],seed:[{id:"1",title:"اختبار القرآن الشهري",subtitle:"تقييم الحفظ والمراجعة",status:"مفتوح"},{id:"2",title:"اختبار القراءة",subtitle:"تقييم القراءة والنطق",status:"مسودة"}]},
  paths:{title:"المسارات التعليمية",subtitle:"نظّم المواد والمراحل التعليمية واربط الطلاب بالمسار المناسب.",primary:"إضافة مسار",tabs:["المسارات","المواد","المراحل"],stats:[["مسارات نشطة","0"],["مواد","0"],["طلاب مرتبطون","0"],["مراحل مكتملة","0"]],columns:["المسار","الوصف","الحالة","الإجراء"],seed:[{id:"1",title:"القرآن الكريم",subtitle:"حفظ ومراجعة وتلاوة",status:"نشط"},{id:"2",title:"اللغة العربية",subtitle:"قراءة وقواعد ومفردات",status:"نشط"}]},
  reports:{title:"التقارير",subtitle:"أنشئ تقارير الحصص والطلاب والساعات واحتفظ بسجل واضح لكل شهر.",primary:"إنشاء تقرير",tabs:["تقارير الطلاب","تقارير الحصص","تقارير المراكز"],stats:[["تقارير هذا الشهر","0"],["جاهزة للإرسال","0"],["مسودات","0"],["تمت مشاركتها","0"]],columns:["التقرير","الطالب / الجهة","الحالة","الإجراء"],seed:[{id:"1",title:"التقرير الشهري",subtitle:"ملخص ساعات الطالب",status:"مسودة"},{id:"2",title:"تقرير مركز",subtitle:"تقرير اكتمال الساعات",status:"جاهز"}]},
  alerts:{title:"التنبيهات والتذكيرات",subtitle:"أنشئ تنبيهات للحصص والمراجعات والمهام المهمة.",primary:"إضافة تنبيه",tabs:["التنبيهات","القادمة","السجل"],stats:[["تنبيهات نشطة","0"],["اليوم","0"],["تمت قراءتها","0"],["مؤجلة","0"]],columns:["التنبيه","الموعد","الحالة","الإجراء"],seed:[{id:"1",title:"مراجعة الحفظ",subtitle:"قبل الحصة القادمة",status:"نشط"},{id:"2",title:"تذكير بحصة",subtitle:"قبل الموعد بـ 30 دقيقة",status:"نشط"}]},
  settings:{title:"الإعدادات",subtitle:"خصّص إعدادات رواق ومعلومات الحساب والتنبيهات والتفضيلات.",primary:"حفظ التغييرات",tabs:["الحساب","التفضيلات","التنبيهات"],stats:[["اللغة","العربية"],["المنطقة الزمنية","محلية"],["التذكيرات","30 دقيقة"],["الحساب","نشط"]],columns:["الإعداد","القيمة","الحالة",""],seed:[{id:"1",title:"المنطقة الزمنية",subtitle:"تُستخدم في عرض مواعيد الطلاب",status:"مفعل",value:"حسب الجهاز"},{id:"2",title:"التذكير قبل الحصة",subtitle:"إشعار تلقائي",status:"مفعل",value:"30 دقيقة"},{id:"3",title:"لغة الواجهة",subtitle:"اللغة الأساسية",status:"مفعل",value:"العربية"}]},
  "my-calendar":{title:"جدولي الشخصي",subtitle:"أضف مواعيدك الشخصية ومهام الحفظ والمراجعة إلى جانب حصص الطلاب.",primary:"إضافة موعد",tabs:["اليوم","الأسبوع","المواعيد الشخصية"],stats:[["مواعيد اليوم","0"],["هذا الأسبوع","0"],["وقت متاح","—"],["تذكيرات","0"]],columns:["الموعد","التاريخ","الحالة","الإجراء"],seed:[{id:"1",title:"مراجعة شخصية",subtitle:"ورد القرآن",status:"قادم"},{id:"2",title:"مهمة",subtitle:"تحضير الدروس",status:"قادم"}]},
  lessons:{title:"الحصص",subtitle:"سجل الحصص المنجزة وتابع الحصص القادمة وبيانات كل جلسة.",primary:"تسجيل حصة",tabs:["القادمة","المنجزة","السجل"],stats:[["اليوم","0"],["هذا الأسبوع","0"],["منجزة","0"],["معلقة","0"]],columns:["الحصة","الطالب","الحالة","الإجراء"],seed:[{id:"1",title:"حصة قرآن",subtitle:"طالب",status:"قادم"},{id:"2",title:"حصة لغة عربية",subtitle:"طالب",status:"منجز"}]}
};

function read(kind:Kind, seed:Row[]){try{const raw=localStorage.getItem(`riwaq:${kind}`);return raw?JSON.parse(raw):seed}catch{return seed}}
export default function ManagementModule({kind}:{kind:Kind}){
  const c=config[kind], Icon=icons[kind];
  const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[tab,setTab]=useState(0),[open,setOpen]=useState(false),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState({title:"",subtitle:"",status:"نشط",date:""});
  useEffect(()=>setRows(read(kind,c.seed)),[kind]);
  useEffect(()=>{if(rows.length)localStorage.setItem(`riwaq:${kind}`,JSON.stringify(rows))},[rows,kind]);
  const filtered=useMemo(()=>rows.filter(r=>`${r.title} ${r.subtitle}`.includes(query.trim())),[rows,query]);
  const save=()=>{if(!form.title.trim())return;const next:Row={id:editing?.id||crypto.randomUUID(),title:form.title.trim(),subtitle:form.subtitle.trim()||"بدون وصف",status:form.status,date:form.date||undefined};setRows(v=>editing?v.map(r=>r.id===editing.id?next:r):[next,...v]);setOpen(false);setEditing(null);setForm({title:"",subtitle:"",status:"نشط",date:""})};
  const start=(row?:Row)=>{setEditing(row||null);setForm(row?{title:row.title,subtitle:row.subtitle,status:row.status,date:row.date||""}:{title:"",subtitle:"",status:"نشط",date:""});setOpen(true)};
  return <main className="management-page" dir="rtl">
    <section className="management-hero"><div><span className="eyebrow"><Icon size={14}/> إدارة رواق</span><h1>{c.title}</h1><p>{c.subtitle}</p></div><button className="primary-button management-primary" onClick={()=>start()}><Plus size={17}/>{c.primary}</button></section>
    <section className="management-tabs"><div>{c.tabs.map((t,i)=><button key={t} onClick={()=>setTab(i)} className={tab===i?"active":""}>{t}</button>)}</div><span>آخر تحديث الآن</span></section>
    <section className="management-stats">{c.stats.map(([label,value],i)=><article key={label} className={i===0?"featured":""}><span>{label}</span><strong>{value}</strong><small>{i===0?"ملخص الفترة الحالية":"جاهز للمتابعة"}</small></article>)}</section>
    <section className="management-panel"><header><div><h2>{c.tabs[tab]}</h2><p>{rows.length} عنصر في هذا القسم</p></div><div className="management-tools"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث..."/></label><button className="secondary-button"><CalendarDays size={15}/> سبتمبر 2026 <ChevronDown size={14}/></button></div></header>
      <div className="management-grid">{filtered.map(r=><article key={r.id} className="management-card"><div className="card-icon"><Icon size={20}/></div><div className="card-copy"><h3>{r.title}</h3><p>{r.subtitle}</p></div><span className={`management-status ${r.status.includes("مكتمل")||r.status.includes("منجز")||r.status.includes("جاهز")?"done":""}`}>{r.status}</span>{r.value&&<div className="management-value">{r.value}</div>}<footer><button onClick={()=>start(r)}>عرض وتعديل</button><button className="icon-delete" onClick={()=>setRows(v=>v.filter(x=>x.id!==r.id))}><Trash2 size={15}/></button></footer></article>)}</div>
    </section>
    {open&&<div className="management-modal-backdrop"><section className="management-modal"><header><div><span className="modal-icon"><Icon size={18}/></span><div><h2>{editing?"تعديل العنصر":c.primary}</h2><p>{c.title}</p></div></div><button onClick={()=>setOpen(false)}><X size={19}/></button></header><div className="management-form"><label>العنوان<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="اكتب العنوان"/></label><label>التفاصيل<textarea value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} placeholder="تفاصيل إضافية"/></label><div className="two-fields"><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>نشط</option><option>قادم</option><option>مسودة</option><option>مكتمل</option><option>معلق</option></select></label><label>التاريخ<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div></div><footer><button className="secondary-button" onClick={()=>setOpen(false)}>إلغاء</button><button className="primary-button" onClick={save}><CheckCircle2 size={16}/> حفظ</button></footer></section></div>}
  </main>
}
