"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Check, Clock3, Plus, Trash2, BookOpen, GraduationCap, Brain, NotebookPen, User, ChevronRight, ChevronLeft, CalendarDays } from "lucide-react";
import { createTeacherBlock, deleteTeacherBlock, getTeacherBlocks } from "../lib/data";

type Block = { id: string; title: string; starts_at: string; ends_at: string; block_type: string; notes?: string | null; _baseId?: string; _recurring?: boolean };
type RepeatMeta = { type: "daily" | "weekly"; days?: number[] };
const REPEAT_PREFIX = "[[USTADH_REPEAT:";
const TYPES = [["memorization", "حفظ قرآن", "green"], ["revision", "مراجعة قرآن", "blue"], ["study", "درس علم", "brown"], ["prep", "تحضير / مطالعة", "purple"], ["teaching", "تدريس", "orange"], ["personal", "شخصي", "gray"], ["other", "أخرى", "gray"]] as const;
const labels: Record<string, string> = Object.fromEntries(TYPES.map((x) => [x[0], x[1]]));
const dayNames = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
function duration(a: string, b: string) { return Math.max(0, (new Date(b).getTime() - new Date(a).getTime()) / 60000); }
function durText(m: number) { const h = Math.floor(m / 60); const min = Math.round(m % 60); return h ? `${h}س${min ? ` ${min}د` : ""}` : `${min}د`; }
function icon(t: string) { if (t === "memorization") return <BookOpen size={17} />; if (t === "revision") return <Check size={17} />; if (t === "study") return <GraduationCap size={17} />; if (t === "prep") return <NotebookPen size={17} />; if (t === "teaching") return <Brain size={17} />; return <User size={17} />; }
function dateKey(d: Date) { return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`; }
function parseRepeat(notes?: string | null): { meta: RepeatMeta | null; cleanNotes: string } { if (!notes?.startsWith(REPEAT_PREFIX)) return { meta: null, cleanNotes: notes || "" }; const end = notes.indexOf("]]", REPEAT_PREFIX.length); if (end < 0) return { meta: null, cleanNotes: notes || "" }; try { const meta = JSON.parse(notes.slice(REPEAT_PREFIX.length, end)) as RepeatMeta; return { meta, cleanNotes: notes.slice(end + 2).trim() }; } catch { return { meta: null, cleanNotes: notes || "" }; } }
function encodedNotes(notes: string, repeat: string, days: number[]) { if (repeat === "once") return notes || null; const meta: RepeatMeta = repeat === "daily" ? { type: "daily" } : { type: "weekly", days }; return `${REPEAT_PREFIX}${JSON.stringify(meta)}]]${notes ? ` ${notes}` : ""}`; }
function expandBlocks(source: Block[], from: Date, to: Date): Block[] { const out: Block[] = []; for (const base of source) { const { meta, cleanNotes } = parseRepeat(base.notes); const start = new Date(base.starts_at), end = new Date(base.ends_at); if (!meta) { if (dateKey(start) >= dateKey(from) && dateKey(start) <= dateKey(to)) out.push({ ...base, notes: cleanNotes }); continue; } const length = end.getTime() - start.getTime(); const cursor = new Date(Math.max(start.getTime(), from.getTime())); cursor.setHours(0, 0, 0, 0); for (let i = 0; i <= 370 && cursor <= to; i++, cursor.setDate(cursor.getDate() + 1)) { if (cursor < new Date(start.getFullYear(), start.getMonth(), start.getDate())) continue; const matches = meta.type === "daily" || (meta.days || []).includes(cursor.getDay()); if (!matches) continue; const instanceStart = new Date(cursor); instanceStart.setHours(start.getHours(), start.getMinutes(), start.getSeconds(), start.getMilliseconds()); const instanceEnd = new Date(instanceStart.getTime() + length); out.push({ ...base, id: `${base.id}_${dateKey(cursor)}`, _baseId: base.id, _recurring: true, starts_at: instanceStart.toISOString(), ends_at: instanceEnd.toISOString(), notes: cleanNotes }); } } return out; }

export default function PersonalScheduleV2() {
  const [blocks, setBlocks] = useState<Block[]>([]); const [selected, setSelected] = useState(new Date()); const [view, setView] = useState<"day" | "week">("day"); const [show, setShow] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [form, setForm] = useState({ title: "", start: "", end: "", type: "memorization", notes: "", repeat: "once", days: [] as number[] });
  const load = async () => { setLoading(true); const r = await getTeacherBlocks(); if (r.error) setError(r.error.message); else setBlocks((r.data || []) as Block[]); setLoading(false); };
  useEffect(() => { load(); }, []);
  const weekDays = useMemo(() => { const d = new Date(selected); d.setDate(d.getDate() - d.getDay()); return Array.from({ length: 7 }, (_, i) => { const x = new Date(d); x.setDate(d.getDate() + i); return x; }); }, [selected]);
  const visibleBlocks = useMemo(() => expandBlocks(blocks, weekDays[0], weekDays[6]), [blocks, weekDays]);
  const dayBlocks = useMemo(() => visibleBlocks.filter((b) => dateKey(new Date(b.starts_at)) === dateKey(selected)).sort((a, b) => new Date(a.starts_at).getTime() - new Date(b.starts_at).getTime()), [visibleBlocks, selected]);
  const stats = useMemo(() => { const out: Record<string, number> = {}; dayBlocks.forEach((b) => { out[b.block_type] = (out[b.block_type] || 0) + duration(b.starts_at, b.ends_at); }); return out; }, [dayBlocks]);
  const weekStats = useMemo(() => { const out: Record<string, number> = {}; visibleBlocks.forEach((b) => { out[b.block_type] = (out[b.block_type] || 0) + duration(b.starts_at, b.ends_at); }); return out; }, [visibleBlocks]);
  const total = dayBlocks.reduce((n, b) => n + duration(b.starts_at, b.ends_at), 0); const weekTotal = visibleBlocks.reduce((n, b) => n + duration(b.starts_at, b.ends_at), 0);
  async function add(e: FormEvent) { e.preventDefault(); setError(""); if (!form.title || !form.start || !form.end) return; if (form.repeat === "weekly" && !form.days.length) { setError("اختر يومًا واحدًا على الأقل للتكرار الأسبوعي"); return; } const date = `${selected.getFullYear()}-${String(selected.getMonth() + 1).padStart(2, "0")}-${String(selected.getDate()).padStart(2, "0")}`; const s = new Date(`${date}T${form.start}:00`), en = new Date(`${date}T${form.end}:00`); if (en <= s) { setError("وقت النهاية يجب أن يكون بعد البداية"); return; } const r = await createTeacherBlock({ title: form.title, starts_at: s.toISOString(), ends_at: en.toISOString(), block_type: form.type, notes: encodedNotes(form.notes, form.repeat, form.days) }); if (r.error) setError(r.error.message); else { setForm({ title: "", start: "", end: "", type: "memorization", notes: "", repeat: "once", days: [] }); setShow(false); load(); } }
  async function remove(id: string) { if (!confirm("حذف هذا النشاط؟")) return; const baseId = id.includes("_") ? id.split("_")[0] : id; const r = await deleteTeacherBlock(baseId); if (r.error) setError(r.error.message); else load(); }
  function move(n: number) { const d = new Date(selected); d.setDate(d.getDate() + n); setSelected(d); } function isToday(d: Date) { return dateKey(d) === dateKey(new Date()); }
  return <section className="personal-v2" dir="rtl">
    <div className="hero"><div><p className="eyebrow">الإدارة</p><h2>جدولي الشخصي</h2><p>خطط لحفظك ومراجعتك وطلبك للعلم وتدريسك، مع رؤية واضحة للوقت الذي تنفقه كل يوم وأسبوع.</p></div><button className="primary-btn" onClick={() => setShow(true)}><Plus size={17} /> إضافة نشاط</button></div>
    <div className="view-switch"><div className="segmented"><button className={view === "day" ? "active" : ""} onClick={() => setView("day")}>اليوم</button><button className={view === "week" ? "active" : ""} onClick={() => setView("week")}>الأسبوع</button></div><button className="today-btn" onClick={() => setSelected(new Date())}><CalendarDays size={15} /> اليوم</button></div>
    <div className="day-bar"><button className="outline-btn" onClick={() => move(view === "week" ? -7 : -1)}><ChevronRight size={15} /> السابق</button><div><b>{selected.toLocaleDateString("ar-EG", { weekday: "long", day: "numeric", month: "long" })}</b><span>{selected.toLocaleDateString("ar-EG")}</span></div><button className="outline-btn" onClick={() => move(view === "week" ? 7 : 1)}>التالي <ChevronLeft size={15} /></button></div>
    <div className="stats-row"><div className="stat-card"><span>{view === "day" ? "إجمالي اليوم" : "إجمالي الأسبوع"}</span><b>{durText(view === "day" ? total : weekTotal)}</b></div><div className="stat-card"><span>القرآن</span><b>{durText(view === "day" ? (stats.memorization || 0) + (stats.revision || 0) : (weekStats.memorization || 0) + (weekStats.revision || 0))}</b></div><div className="stat-card"><span>العلم</span><b>{durText(view === "day" ? (stats.study || 0) + (stats.prep || 0) : (weekStats.study || 0) + (weekStats.prep || 0))}</b></div><div className="stat-card"><span>التدريس</span><b>{durText(view === "day" ? stats.teaching || 0 : weekStats.teaching || 0)}</b></div></div>
    {view === "day" ? <><div className="goals-card"><div><h3>خطة اليوم</h3><p>اجعل أعمالك واضحة ومحددة بزمن: حفظ، مراجعة، علم، تحضير، وتدريس.</p></div><button className="outline-btn" onClick={() => setShow(true)}><Plus size={15} /> إضافة نشاط</button></div>{error && <p className="login-error">{error}</p>}<div className="timeline-card"><div className="timeline-head"><h3>الجدول الزمني</h3><span>{dayBlocks.length} نشاط · {durText(total)}</span></div>{loading ? <p className="muted">جاري التحميل…</p> : dayBlocks.length === 0 ? <div className="empty-state"><Clock3 size={28} /><b>اليوم فارغ</b><span>أضف أول نشاط وحدد بدايته ونهايته، وسيظهر هنا كفترة زمنية.</span><button className="primary-btn" onClick={() => setShow(true)}><Plus size={16} /> إضافة نشاط</button></div> : <div className="timeline">{dayBlocks.map((b) => { const t = TYPES.find((x) => x[0] === b.block_type) || TYPES[6]; return <div className={`timeline-item type-${t[2]}`} key={b.id}><div className="timeline-time"><b>{new Date(b.starts_at).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}</b><span>{new Date(b.ends_at).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}</span></div><div className="timeline-dot">{icon(b.block_type)}</div><div className="timeline-block"><div className="timeline-title"><div><b>{b.title}</b><span>{labels[b.block_type] || "أخرى"} · {durText(duration(b.starts_at, b.ends_at))}{b._recurring ? " · متكرر" : ""}</span></div><button className="mini-btn" onClick={() => remove(b._baseId || b.id)} aria-label="حذف"><Trash2 size={14} /></button></div>{b.notes && <p>{b.notes}</p>}</div></div>; })}</div>}</div></> : <div className="week-grid">{weekDays.map((d) => { const ds = visibleBlocks.filter((b) => dateKey(new Date(b.starts_at)) === dateKey(d)); return <button key={dateKey(d)} className={`week-day ${isToday(d) ? "today" : ""} ${dateKey(d) === dateKey(selected) ? "selected" : ""}`} onClick={() => { setSelected(d); setView("day"); }}><span>{dayNames[d.getDay()]}</span><b>{d.getDate()}</b><small>{ds.length ? `${ds.length} نشاط · ${durText(ds.reduce((n, x) => n + duration(x.starts_at, x.ends_at), 0))}` : "فارغ"}</small><div>{ds.slice(0, 3).map((b) => <i key={b.id} className={`dot-${(TYPES.find((x) => x[0] === b.block_type) || TYPES[6])[2]}`} />)}</div></button>; })}</div>}
    {show && <div className="modal-backdrop" onMouseDown={(e) => e.currentTarget === e.target && setShow(false)}><form className="card form activity-modal" onSubmit={add}><div className="modal-head"><div><p className="eyebrow">{selected.toLocaleDateString("ar-EG")}</p><h3>إضافة نشاط</h3></div><button type="button" className="mini-btn" onClick={() => setShow(false)}>×</button></div><label>اسم النشاط<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="مثال: حفظ سورة العاديات 1–11" required /></label><div className="form-grid"><label>النوع<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{TYPES.map((t) => <option value={t[0]} key={t[0]}>{t[1]}</option>)}</select></label><label>من<input type="time" value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })} required /></label><label>إلى<input type="time" value={form.end} onChange={(e) => setForm({ ...form, end: e.target.value })} required /></label></div><label>التكرار<select value={form.repeat} onChange={(e) => setForm({ ...form, repeat: e.target.value, days: e.target.value === "weekly" ? [] : form.days })}><option value="once">مرة واحدة</option><option value="daily">يوميًا</option><option value="weekly">أسبوعيًا</option></select></label>{form.repeat === "weekly" && <div className="repeat-days"><div className="repeat-days-head"><b>اختر أيام التكرار</b><span>يمكن اختيار أكثر من يوم</span></div><div className="day-picker" style={{ display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: "10px", marginTop: "12px" }}>{dayNames.map((name, i) => { const active = form.days.includes(i); return <button type="button" key={name} className={`day-choice ${active ? "active" : ""}`} aria-pressed={active} onClick={() => setForm((f) => ({ ...f, days: f.days.includes(i) ? f.days.filter((x) => x !== i) : [...f.days, i] }))} style={{ minWidth: 0, minHeight: "74px", padding: "10px 6px", borderRadius: "14px", border: active ? "2px solid var(--accent)" : "1px solid var(--line)", background: active ? "var(--soft)" : "#fff", color: active ? "var(--accent-dark)" : "var(--ink)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "5px", fontWeight: active ? 700 : 500, boxShadow: active ? "0 0 0 3px rgba(102,121,91,.10)" : "0 1px 3px rgba(25,45,28,.04)", transition: "all .18s ease" }}><span style={{ fontSize: "18px", fontWeight: 800 }}>{name}</span>{active && <Check size={16} />}</button>; })}</div></div>}<label>ملاحظات<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="السورة والآيات، الكتاب والباب، الصفحات، أو أي ملاحظة…" /></label><div className="modal-actions"><button type="button" className="outline-btn" onClick={() => setShow(false)}>إلغاء</button><button className="primary-btn"><Plus size={16} /> حفظ النشاط</button></div></form></div>}
  </section>;
}
