"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Check, Clock3, Plus, Trash2, BookOpen, GraduationCap, Brain, NotebookPen, User, ChevronRight, ChevronLeft, CalendarDays } from "lucide-react";
import { createTeacherBlock, deleteTeacherBlock, getTeacherBlocks } from "../lib/data";

type Block={id:string;title:string;starts_at:string;ends_at:string;block_type:string;notes?:string|null};
type Repeat={type:"daily"|"weekly";days?:number[]};
const PREFIX="[[USTADH_REPEAT:";
const TYPES=[ ["memorization","حفظ قرآن","green"],["revision","مراجعة قرآن","blue"],["study","درس علم","brown"],["prep","تحضير / مطالعة","purple"],["teaching","تدريس","orange"],["personal","شخصي","gray"],["other","أخرى","gray"] ] as const;
const labels=Object.fromEntries(TYPES.map(x=>[x[0],x[1]]));
const days=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const dateKey=(d:Date)=>`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
const mins=(a:string,b:string)=>Math.max(0,(Date.parse(b)-Date.parse(a))/60000);
const dur=(m:number)=>{const h=Math.floor(m/60),n=Math.round(m%60);return h?`${h}س${n?` ${n}د`:""}`:`${n}د`};
function icon(t:string){if(t==="memorization")return <BookOpen size={17}/>;if(t==="revision")return <Check size={17}/>;if(t==="study")return <GraduationCap size={17}/>;if(t==="prep")return <NotebookPen size={17}/>;if(t==="teaching")return <Brain size={17}/>;return <User size={17}/>}
function parse(notes?:string|null){if(!notes?.startsWith(PREFIX))return {repeat:null as Repeat|null,notes:notes||""};const end=notes.indexOf("]]",PREFIX.length);if(end<0)return {repeat:null,notes:notes||""};try{return {repeat:JSON.parse(notes.slice(PREFIX.length,end)) as Repeat,notes:notes.slice(end+2).trim()}}catch{return {repeat:null,notes:notes||""}}}
function encode(notes:string,repeat:string,selected:number[]){if(repeat==="once")return notes||null;const r:Repeat=repeat==="daily"?{type:"daily"}:{type:"weekly",days:[...selected].sort((a,b)=>a-b)};return `${PREFIX}${JSON.stringify(r)}]]${notes?` ${notes}`:""}`}
function expand(base:Block[],from:Date,to:Date){const out:Block[]=[];for(const b of base){const p=parse(b.notes),s=new Date(b.starts_at),e=new Date(b.ends_at),length=e.getTime()-s.getTime();if(!p.repeat){if(dateKey(s)>=dateKey(from)&&dateKey(s)<=dateKey(to))out.push({...b,notes:p.notes});continue}const cursor=new Date(from);cursor.setHours(0,0,0,0);const first=new Date(s);first.setHours(0,0,0,0);for(let i=0;i<400&&cursor<=to;i++,cursor.setDate(cursor.getDate()+1)){if(cursor<first)continue;const match=p.repeat.type==="daily"||(p.repeat.type==="weekly"&&(p.repeat.days||[]).includes(cursor.getDay()));if(!match)continue;const a=new Date(cursor);a.setHours(s.getHours(),s.getMinutes(),s.getSeconds(),s.getMilliseconds());const z=new Date(a.getTime()+length);out.push({...b,id:`${b.id}_${dateKey(cursor)}`,starts_at:a.toISOString(),ends_at:z.toISOString(),notes:p.notes});}}return out}
export default function PersonalScheduleV3(){
 const [blocks,setBlocks]=useState<Block[]>([]),[selected,setSelected]=useState(new Date()),[view,setView]=useState<"day"|"week">("day"),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [form,setForm]=useState({title:"",start:"",end:"",type:"memorization",notes:"",repeat:"once",days:[] as number[]});
 const load=async()=>{setLoading(true);const r=await getTeacherBlocks();if(r.error)setError(r.error.message);else setBlocks((r.data||[]) as Block[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const week=useMemo(()=>{const d=new Date(selected);d.setDate(d.getDate()-d.getDay());return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x})},[selected]);
 const visible=useMemo(()=>expand(blocks,week[0],week[6]),[blocks,week]);
 const day=useMemo(()=>visible.filter(b=>dateKey(new Date(b.starts_at))===dateKey(selected)).sort((a,b)=>Date.parse(a.starts_at)-Date.parse(b.starts_at)),[visible,selected]);
 const stats=useMemo(()=>{const x:Record<string,number>={};day.forEach(b=>x[b.block_type]=(x[b.block_type]||0)+mins(b.starts_at,b.ends_at));return x},[day]);
 const ws=useMemo(()=>{const x:Record<string,number>={};visible.forEach(b=>x[b.block_type]=(x[b.block_type]||0)+mins(b.starts_at,b.ends_at));return x},[visible]);
 const total=day.reduce((n,b)=>n+mins(b.starts_at,b.ends_at),0),weekTotal=visible.reduce((n,b)=>n+mins(b.starts_at,b.ends_at),0);
 async function add(e:FormEvent){e.preventDefault();setError("");if(!form.title||!form.start||!form.end)return;if(form.repeat==="weekly"&&!form.days.length){setError("اختر يومًا واحدًا على الأقل");return}const d=`${selected.getFullYear()}-${String(selected.getMonth()+1).padStart(2,"0")}-${String(selected.getDate()).padStart(2,"0")}`,s=new Date(`${d}T${form.start}:00`),z=new Date(`${d}T${form.end}:00`);if(z<=s){setError("وقت النهاية يجب أن يكون بعد البداية");return}const r=await createTeacherBlock({title:form.title,starts_at:s.toISOString(),ends_at:z.toISOString(),block_type:form.type,notes:encode(form.notes,form.repeat,form.days)});if(r.error)setError(r.error.message);else{setForm({title:"",start:"",end:"",type:"memorization",notes:"",repeat:"once",days:[]});setShow(false);await load()}}
 async function remove(id:string){if(!confirm("حذف هذا النشاط؟"))return;const base=id.split("_")[0],r=await deleteTeacherBlock(base);if(r.error)setError(r.error.message);else load()}
 const move=(n:number)=>{const d=new Date(selected);d.setDate(d.getDate()+n);setSelected(d)};
 return <section className="personal-v2" dir="rtl">
  <div className="hero"><div><p className="eyebrow">الإدارة</p><h2>جدولي الشخصي</h2><p>خطط لحفظك ومراجعتك وطلبك للعلم وتدريسك.</p></div><button className="primary-btn" onClick={()=>setShow(true)}><Plus size={17}/> إضافة نشاط</button></div>
  <div className="view-switch"><div className="segmented"><button className={view==="day"?"active":""} onClick={()=>setView("day")}>اليوم</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>الأسبوع</button></div><button className="today-btn" onClick={()=>setSelected(new Date())}><CalendarDays size={15}/> اليوم</button></div>
  <div className="day-bar"><button className="outline-btn" onClick={()=>move(view==="week"?-7:-1)}><ChevronRight size={15}/> السابق</button><div><b>{selected.toLocaleDateString("ar-EG",{weekday:"long",day:"numeric",month:"long"})}</b><span>{selected.toLocaleDateString("ar-EG")}</span></div><button className="outline-btn" onClick={()=>move(view==="week"?7:1)}>التالي <ChevronLeft size={15}/></button></div>
  <div className="stats-row"><div className="stat-card"><span>{view==="day"?"إجمالي اليوم":"إجمالي الأسبوع"}</span><b>{dur(view==="day"?total:weekTotal)}</b></div><div className="stat-card"><span>القرآن</span><b>{dur(view==="day"?(stats.memorization||0)+(stats.revision||0):(ws.memorization||0)+(ws.revision||0))}</b></div><div className="stat-card"><span>العلم</span><b>{dur(view==="day"?(stats.study||0)+(stats.prep||0):(ws.study||0)+(ws.prep||0))}</b></div><div className="stat-card"><span>التدريس</span><b>{dur(view==="day"?stats.teaching||0:ws.teaching||0)}</b></div></div>
  {error&&<p className="login-error">{error}</p>}
  {view==="day"?<><div className="goals-card"><div><h3>خطة اليوم</h3><p>الحفظ، المراجعة، العلم، التحضير، والتدريس.</p></div><button className="outline-btn" onClick={()=>setShow(true)}><Plus size={15}/> إضافة نشاط</button></div><div className="timeline-card"><div className="timeline-head"><h3>الجدول الزمني</h3><span>{day.length} نشاط · {dur(total)}</span></div>{loading?<p className="muted">جاري التحميل…</p>:!day.length?<div className="empty-state"><Clock3 size={28}/><b>اليوم فارغ</b><span>أضف أول نشاط وحدد وقته.</span></div>:<div className="timeline">{day.map(b=>{const t=TYPES.find(x=>x[0]===b.block_type)||TYPES[6];return <div className={`timeline-item type-${t[2]}`} key={b.id}><div className="timeline-time"><b>{new Date(b.starts_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</b><span>{new Date(b.ends_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</span></div><div className="timeline-dot">{icon(b.block_type)}</div><div className="timeline-block"><div className="timeline-title"><div><b>{b.title}</b><span>{labels[b.block_type]||"أخرى"} · {dur(mins(b.starts_at,b.ends_at))}{parse(b.notes).repeat?" · متكرر":""}</span></div><button className="mini-btn" onClick={()=>remove(b.id)}><Trash2 size={14}/></button></div>{b.notes&&<p>{b.notes}</p>}</div></div>})}</div>}</div></>:<div className="week-grid">{week.map(d=>{const ds=visible.filter(b=>dateKey(new Date(b.starts_at))===dateKey(d));return <button key={dateKey(d)} className={`week-day ${dateKey(d)===dateKey(new Date())?"today":""} ${dateKey(d)===dateKey(selected)?"selected":""}`} onClick={()=>{setSelected(d);setView("day")}}><span>{days[d.getDay()]}</span><b>{d.getDate()}</b><small>{ds.length?`${ds.length} نشاط · ${dur(ds.reduce((n,b)=>n+mins(b.starts_at,b.ends_at),0))}`:"فارغ"}</small><div>{ds.slice(0,3).map(b=><i key={b.id} className={`dot-${(TYPES.find(x=>x[0]===b.block_type)||TYPES[6])[2]}`}/>)}</div></button>})}</div>}
  {show&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setShow(false)}><form className="card form activity-modal" onSubmit={add}><div className="modal-head"><div><p className="eyebrow">{selected.toLocaleDateString("ar-EG")}</p><h3>إضافة نشاط</h3></div><button type="button" className="mini-btn" onClick={()=>setShow(false)}>×</button></div><label>اسم النشاط<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><div className="form-grid"><label>النوع<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(t=><option value={t[0]} key={t[0]}>{t[1]}</option>)}</select></label><label>من<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})} required/></label><label>إلى<input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})} required/></label></div><label>التكرار<select value={form.repeat} onChange={e=>setForm({...form,repeat:e.target.value,days:e.target.value==="weekly"?[]:form.days})}><option value="once">مرة واحدة</option><option value="daily">يوميًا</option><option value="weekly">أسبوعيًا</option></select></label>{form.repeat==="weekly"&&<div className="repeat-days"><div className="repeat-days-head"><b>اختر أيام التكرار</b><span>اختر يومًا أو أكثر</span></div><div className="day-picker" style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:10,marginTop:12}}>{days.map((name,i)=>{const active=form.days.includes(i);return <button type="button" key={name} aria-pressed={active} onClick={()=>setForm(f=>({...f,days:f.days.includes(i)?f.days.filter(x=>x!==i):[...f.days,i]}))} style={{minWidth:0,minHeight:74,padding:"10px 6px",borderRadius:14,border:active?"2px solid var(--accent)":"1px solid var(--line)",background:active?"var(--soft)":"#fff",color:active?"var(--accent-dark)":"var(--ink)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5,fontWeight:active?700:500}}><span style={{fontSize:18,fontWeight:800}}>{name}</span>{active&&<Check size={16}/>}</button>})}</div></div>}<label>ملاحظات<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="outline-btn" onClick={()=>setShow(false)}>إلغاء</button><button className="primary-btn"><Plus size={16}/> حفظ النشاط</button></div></form></div>}
 </section>
}
