"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Globe2, Plus, Search, Users, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createStudent, deleteStudent, getStudents, updateStudent } from "../../lib/data";
import { COUNTRIES, countryName, countryTimezone } from "../../lib/countries";

type Student={id:string;full_name:string;age:number|null;country_code:string|null;timezone:string;native_language:string|null;monthly_hours:number;status:string;contact_name:string|null;contact_email:string|null;contact_phone:string|null;notes:string|null};
const STATUS:[string,string][]=[["active","نشط"],["paused","موقوف مؤقتًا"],["waiting","قائمة انتظار"],["archived","مؤرشف"]];
export default function StudentsPage(){
 const [students,setStudents]=useState<Student[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[open,setOpen]=useState(false),[editing,setEditing]=useState<Student|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const r=await getStudents();if(r.error)setError(r.error.message);else setStudents((r.data||[]) as Student[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>students.filter(s=>(status==="all"||s.status===status)&&`${s.full_name} ${countryName(s.country_code)} ${s.native_language||""}`.toLowerCase().includes(q.toLowerCase())),[students,status,q]);
 async function remove(id:string){if(!confirm("حذف الطالب نهائيًا؟ ستُحذف بياناته المرتبطة أيضًا."))return;const r=await deleteStudent(id);if(r.error)alert(r.error.message);else load()}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">إدارة الطلاب</p><h2>الطلاب</h2><p className="muted">ملفات الطلاب، الحالات، اللغات، الساعات والبيانات الخاصة بولي الأمر.</p></div><div className="top-actions"><button className="primary-btn" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/> طالب جديد</button></div></section>
 <div className="card search-card"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو الدولة أو اللغة..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">كل الحالات</option>{STATUS.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>
 {loading?<div className="empty card"><Users size={28}/><h2>جاري التحميل…</h2></div>:filtered.length?<div className="student-grid">{filtered.map(s=><article className="card student-card" key={s.id}><div className="student-card-head"><div className="avatar">{s.full_name[0]}</div><div><h3>{s.full_name}</h3><span>{s.age?`${s.age} سنة`:"—"} · {countryName(s.country_code)} · {s.timezone}</span></div><span className="status">{STATUS.find(x=>x[0]===s.status)?.[1]||s.status}</span></div><div className="chips">{s.native_language&&<span>{s.native_language}</span>}<span>{Number(s.monthly_hours||0)} ساعة/شهر</span></div><div className="student-meta"><span>ولي الأمر</span><b>{s.contact_name||"غير مضاف"}</b></div><div className="modal-actions"><button className="outline-btn" onClick={()=>{setEditing(s);setOpen(true)}}>تعديل</button><Link className="outline-btn" href={`/students/${s.id}`}>الملف الكامل</Link><button className="outline-btn" onClick={()=>remove(s.id)}>حذف</button></div></article>)}</div>:<div className="empty card"><Users size={28}/><h2>لا يوجد طلاب بهذه الشروط</h2><p>يمكنك تغيير البحث أو إضافة طالب جديد.</p></div>}
 {open&&<StudentModal student={editing} close={()=>{setOpen(false);setEditing(null)}} onSaved={()=>{setOpen(false);setEditing(null);load()}}/>}
 </AppShell>
}
function StudentModal({student,close,onSaved}:{student:Student|null;close:()=>void;onSaved:()=>void}){
 const [country,setCountry]=useState(student?.country_code||""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const tz=countryTimezone(country);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const payload={full_name:String(f.get("name")),age:Number(f.get("age"))||null,country_code:country||null,timezone:tz,native_language:String(f.get("language")||"")||null,monthly_hours:Number(f.get("hours"))||0,status:String(f.get("status")),contact_name:String(f.get("contact_name")||"")||null,contact_email:String(f.get("contact_email")||"")||null,contact_phone:String(f.get("contact_phone")||"")||null,notes:String(f.get("notes")||"")||null};const r=student?await updateStudent(student.id,payload):await createStudent(payload);if(r.error)setError(r.error.message);else onSaved();setSaving(false)}
 return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{student?"تعديل ملف الطالب":"ملف طالب جديد"}</p><h3>{student?student.full_name:"إضافة طالب"}</h3></div><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={submit}><div className="form-grid"><Field name="name" label="اسم الطالب" defaultValue={student?.full_name||""} required/><Field name="age" label="العمر" type="number" defaultValue={student?.age??""} placeholder="12 / 18" required/><label className="field"><span>الدولة</span><select value={country} onChange={e=>setCountry(e.target.value)} required><option value="">اختر الدولة</option>{COUNTRIES.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="field"><span>المنطقة الزمنية</span><div className="readonly-field"><Globe2 size={15}/><input value={tz} readOnly/></div></label><Field name="language" label="اللغة الأم" defaultValue={student?.native_language||""} placeholder="Français / Nederlands..."/><Field name="hours" label="الساعات الشهرية" type="number" defaultValue={student?.monthly_hours||""}/><label className="field"><span>حالة الطالب</span><select name="status" defaultValue={student?.status||"active"}>{STATUS.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><h4 className="form-section-title">بيانات ولي الأمر</h4><div className="form-grid"><Field name="contact_name" label="اسم ولي الأمر" defaultValue={student?.contact_name||""}/><Field name="contact_email" label="البريد الإلكتروني" type="email" defaultValue={student?.contact_email||""}/><Field name="contact_phone" label="رقم الهاتف" defaultValue={student?.contact_phone||""}/></div><Field name="notes" label="ملاحظات خاصة" defaultValue={student?.notes||""}/>{error&&<p className="login-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":student?"حفظ التعديلات":"حفظ الطالب"}</button></div></form></div></div>
}
function Field({name,label,placeholder,type="text",required=false,defaultValue}:{name:string;label:string;placeholder?:string;type?:string;required?:boolean;defaultValue?:string|number}){return <label className="field"><span>{label}</span><input name={name} type={type} placeholder={placeholder} required={required} defaultValue={defaultValue}/></label>}
