"use client";
import { useEffect, useState } from "react";
import { Plus, Search, Globe2, X } from "lucide-react";
import AppShell from "../../components/app-shell";
import { createStudent, deleteStudent, getStudents } from "../../lib/data";

const countries=[{code:"BE",name:"بلجيكا",tz:"Europe/Brussels"},{code:"FR",name:"فرنسا",tz:"Europe/Paris"},{code:"NL",name:"هولندا",tz:"Europe/Amsterdam"},{code:"DE",name:"ألمانيا",tz:"Europe/Berlin"},{code:"GB",name:"المملكة المتحدة",tz:"Europe/London"},{code:"CH",name:"سويسرا",tz:"Europe/Zurich"},{code:"CA",name:"كندا",tz:"America/Toronto"},{code:"US",name:"الولايات المتحدة",tz:"America/New_York"},{code:"AE",name:"الإمارات",tz:"Asia/Dubai"},{code:"SA",name:"السعودية",tz:"Asia/Riyadh"},{code:"EG",name:"مصر",tz:"Africa/Cairo"},{code:"MA",name:"المغرب",tz:"Africa/Casablanca"},{code:"DZ",name:"الجزائر",tz:"Africa/Algiers"},{code:"TN",name:"تونس",tz:"Africa/Tunis"}];
type Student={id:string;full_name:string;age:number|null;country_code:string|null;timezone:string;monthly_hours:number;status:string};
export default function StudentsPage(){const [students,setStudents]=useState<Student[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true);async function load(){setLoading(true);const r=await getStudents();if(!r.error)setStudents((r.data||[]) as Student[]);setLoading(false)}useEffect(()=>{load()},[]);const filtered=students.filter(s=>`${s.full_name} ${s.country_code||""}`.toLowerCase().includes(q.toLowerCase()));async function remove(id:string){if(!confirm("حذف الطالب؟"))return;const r=await deleteStudent(id);if(!r.error)load()}
 return <AppShell><section className="page-actions"><div><p className="eyebrow">إدارة الطلاب</p><h2>الطلاب</h2></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> طالب جديد</button></section><div className="card search-card"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو الدولة..."/></div>{loading?<div className="empty card"><h2>جاري التحميل…</h2></div>:filtered.length?<div className="student-grid">{filtered.map(s=><div className="card" key={s.id}><div className="student-card-head"><div className="avatar">{s.full_name[0]}</div><div><h3>{s.full_name}</h3><span>{s.age?`${s.age} سنة`:'—'} · {s.country_code||'—'} · {s.timezone}</span></div><span className="status">{s.status}</span></div><div className="student-meta"><span>الساعات الشهرية</span><b>{s.monthly_hours}</b></div><button className="outline-btn" onClick={()=>remove(s.id)}>حذف</button></div>)}</div>:<div className="empty card"><h2>لا يوجد طلاب</h2><p>ابدأ بإضافة أول طالب.</p><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={16}/> إضافة طالب</button></div>}{open&&<StudentModal close={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</AppShell>}
function StudentModal({close,onSaved}:{close:()=>void;onSaved:()=>void}){const [country,setCountry]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");const tz=countries.find(c=>c.code===country)?.tz||Intl.DateTimeFormat().resolvedOptions().timeZone;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const r=await createStudent({full_name:String(f.get("name")),age:Number(f.get("age"))||null,country_code:country||null,timezone:tz,native_language:String(f.get("language")||"")||null,monthly_hours:Number(f.get("hours"))||0,status:"active"});if(r.error)setError(r.error.message);else onSaved();setSaving(false)}return <div className="overlay"><div className="modal"><div className="modal-head"><h3>إضافة طالب</h3><button className="icon-btn" onClick={close}><X size={18}/></button></div><form className="form" onSubmit={submit}><div className="form-grid"><Field name="name" label="اسم الطالب" required/><Field name="age" label="العمر" type="number" placeholder="12 / 18" required/><label className="field"><span>الدولة</span><select value={country} onChange={e=>setCountry(e.target.value)} required><option value="">اختر الدولة</option>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="field"><span>المنطقة الزمنية</span><div className="readonly-field"><Globe2 size={15}/><input value={tz} readOnly/></div></label><Field name="language" label="اللغة الأم"/><Field name="hours" label="الساعات الشهرية" type="number" placeholder="8"/></div>{error&&<p className="hint">{error}</p>}<div className="modal-actions"><button type="button" className="outline-btn" onClick={close}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الطالب"}</button></div></form></div></div>}
function Field({name,label,placeholder,type="text",required=false}:{name:string;label:string;placeholder?:string;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><input name={name} type={type} placeholder={placeholder} required={required}/></label>}
