"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import * as ct from "countries-and-timezones";
import { Archive, BookOpenCheck, CalendarDays, Check, ChevronLeft, Clock3, FileText, Globe2, Mail, MapPin, Pencil, Phone, Plus, Search, UserRound, Users, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { countryFlag } from "../../lib/country";
import "./students.css";
import "./students-overrides.css";

type Student={id:string;full_name:string;age:number|null;country_code:string|null;timezone:string;native_language:string|null;contact_name:string|null;contact_email:string|null;contact_phone:string|null;monthly_hours:number;status:"active"|"paused"|"archived";notes:string|null;created_at:string};
type Subject={id:string;name_ar:string;name_fr:string|null;name_en:string|null};
type CountryRow={id:string;code:string;name_ar:string;name_en:string|null;timezone:string;teacher_id:string|null;is_active:boolean};
type CountryOption={code:string;nameAr:string;nameEn:string;timezones:string[]};
type DetailLesson={starts_at:string;ends_at:string;title:string;status:string;is_makeup:boolean;notes:string|null;lesson_reports?:{taught_text:string|null;review_text:string|null;homework_text:string|null}[]|null};
type FormState={full_name:string;age:string;country_code:string;timezone:string;native_language:string;contact_name:string;contact_email:string;contact_phone:string;monthly_hours:string;status:"active"|"paused"|"archived";notes:string;subject_ids:string[]};

const regionNames=new Intl.DisplayNames(["ar"],{type:"region"});
const rawPackageCountries=Object.values(ct.getAllCountries() as Record<string,{id:string;name:string;timezones:string[]}>).map(c=>({code:c.id,nameAr:regionNames.of(c.id)||c.name,nameEn:c.name,timezones:c.timezones}));
const palestineSource=rawPackageCountries.find(c=>c.code==="PS");
const packageCountries=[...rawPackageCountries.filter(c=>c.code!=="IL"&&c.code!=="PS"),{code:"PS",nameAr:"فلسطين",nameEn:"Palestine",timezones:palestineSource?.timezones||["Asia/Gaza","Asia/Hebron"]}].sort((a,b)=>a.nameAr.localeCompare(b.nameAr,"ar"));
const emptyForm:FormState={full_name:"",age:"",country_code:"",timezone:"",native_language:"",contact_name:"",contact_email:"",contact_phone:"",monthly_hours:"8",status:"active",notes:"",subject_ids:[]};
const statusLabel={active:"نشط",paused:"متوقف مؤقتًا",archived:"مؤرشف"} as const;
const initials=(n:string)=>n.trim().slice(0,2)||"ط";
const formatDate=(v:string)=>new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v));
const formatTime=(v:string)=>new Intl.DateTimeFormat("ar-EG",{hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const duration=(a:string,b:string)=>Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/60000));

export default function StudentsPage(){
 const [students,setStudents]=useState<Student[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[dbCountries,setDbCountries]=useState<CountryRow[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState<"all"|Student["status"]>("all"),[message,setMessage]=useState("");
 const [formOpen,setFormOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<FormState>(emptyForm);
 const [countryPickerOpen,setCountryPickerOpen]=useState(false),[countryQuery,setCountryQuery]=useState(""),[addCountryOpen,setAddCountryOpen]=useState(false),[addCountryQuery,setAddCountryQuery]=useState(""),[addingCountry,setAddingCountry]=useState(false);
 const [selected,setSelected]=useState<Student|null>(null),[detailTab,setDetailTab]=useState<"overview"|"lessons"|"statement">("overview"),[detailLessons,setDetailLessons]=useState<DetailLesson[]>([]),[detailSubjects,setDetailSubjects]=useState<Subject[]>([]),[detailLoading,setDetailLoading]=useState(false);
 const load=async()=>{setLoading(true);const [s,sub,c]=await Promise.all([supabase.from("students").select("*").order("created_at",{ascending:false}),supabase.from("subjects").select("id,name_ar,name_fr,name_en").eq("is_active",true).order("sort_order",{ascending:true}),supabase.from("countries").select("id,code,name_ar,name_en,timezone,teacher_id,is_active").eq("is_active",true)]);if(!s.error)setStudents((s.data||[]) as Student[]);if(!sub.error)setSubjects((sub.data||[]) as Subject[]);if(!c.error)setDbCountries((c.data||[]).filter((x:any)=>x.code!=="IL") as CountryRow[]);if(s.error)setMessage(s.error.message);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const countries=useMemo<CountryOption[]>(()=>{const map=new Map(packageCountries.map(c=>[c.code,c]));dbCountries.filter(c=>c.code!=="IL").forEach(c=>map.set(c.code,{code:c.code,nameAr:c.name_ar,nameEn:c.name_en||c.name_ar,timezones:[c.timezone]}));return [...map.values()]},[dbCountries]);
 const countryByCode=(code:string)=>countries.find(c=>c.code===code);
 const popularCountries=useMemo(()=>{const counts=new Map<string,number>();students.forEach(s=>{if(s.country_code&&s.country_code!=="IL")counts.set(s.country_code,(counts.get(s.country_code)||0)+1)});return countries.filter(c=>counts.has(c.code)).sort((a,b)=>{const d=(counts.get(b.code)||0)-(counts.get(a.code)||0);return d||a.nameAr.localeCompare(b.nameAr,"ar")}).slice(0,10)},[countries,students]);
 const searchedCountries=useMemo(()=>{const q=countryQuery.trim().toLocaleLowerCase("ar");const base=q?countries.filter(c=>`${c.nameAr} ${c.nameEn} ${c.code}`.toLocaleLowerCase("ar").includes(q)):popularCountries;return base.slice(0,40)},[countries,popularCountries,countryQuery]);
 const allCountriesForAdd=useMemo(()=>{const q=addCountryQuery.trim().toLocaleLowerCase("ar");return countries.filter(c=>!q||`${c.nameAr} ${c.nameEn} ${c.code}`.toLocaleLowerCase("ar").includes(q))},[countries,addCountryQuery]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("ar");return students.filter(s=>(!q||`${s.full_name} ${s.contact_name||""} ${s.contact_email||""}`.toLocaleLowerCase("ar").includes(q))&&(statusFilter==="all"||s.status===statusFilter))},[students,query,statusFilter]);
 const stats=useMemo(()=>({total:students.length,active:students.filter(s=>s.status==="active").length,paused:students.filter(s=>s.status==="paused").length,hours:students.reduce((n,s)=>n+Number(s.monthly_hours||0),0)}),[students]);
 const selectCountry=(code:string)=>{const c=countryByCode(code);if(!c||code==="IL")return;setForm(f=>({...f,country_code:code,timezone:c.timezones[0]||""}));setCountryPickerOpen(false);setCountryQuery("")};
 const openCreate=()=>{const first=popularCountries[0];setEditingId(null);setForm(first?{...emptyForm,country_code:first.code,timezone:first.timezones[0]||""}:{...emptyForm});setCountryPickerOpen(false);setCountryQuery("");setMessage("");setFormOpen(true)};
 const openEdit=async(s:Student)=>{const {data}=await supabase.from("student_subjects").select("subject_id").eq("student_id",s.id);setEditingId(s.id);setForm({full_name:s.full_name,age:s.age?.toString()||"",country_code:s.country_code||"",timezone:s.timezone,native_language:s.native_language||"",contact_name:s.contact_name||"",contact_email:s.contact_email||"",contact_phone:s.contact_phone||"",monthly_hours:String(s.monthly_hours??0),status:s.status,notes:s.notes||"",subject_ids:(data||[]).map((r:any)=>r.subject_id)});setCountryPickerOpen(false);setCountryQuery("");setFormOpen(true)};
 const addCountryFromDirectory=async(code:string)=>{const c=countryByCode(code);if(!c||code==="IL")return;setAddingCountry(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setMessage("انتهت جلسة الدخول.");setAddingCountry(false);return}const existing=dbCountries.find(x=>x.code===code);if(existing){setForm(f=>({...f,country_code:code,timezone:existing.timezone}));setAddCountryOpen(false);setAddCountryQuery("");setCountryPickerOpen(false);setAddingCountry(false);return}const payload={code,name_ar:c.nameAr,name_en:c.nameEn,timezone:c.timezones[0]||"UTC",teacher_id:u.user.id};const {data,error}=await supabase.from("countries").insert(payload).select("id,code,name_ar,name_en,timezone,teacher_id,is_active").single();if(error&&error.code!=="23505"){setMessage(error.message);setAddingCountry(false);return}const saved=(data||{...payload,id:`local-${code}`,is_active:true}) as CountryRow;setDbCountries(prev=>[...prev.filter(x=>x.code!==code),saved]);setForm(f=>({...f,country_code:code,timezone:saved.timezone}));setAddCountryOpen(false);setAddCountryQuery("");setCountryPickerOpen(false);setAddingCountry(false);setMessage(`تمت إضافة ${c.nameAr} واكتشاف المنطقة الزمنية تلقائيًا.`)};
 const saveStudent=async(e:FormEvent)=>{e.preventDefault();if(!form.full_name.trim()||!form.age||!form.country_code||form.country_code==="IL"||!form.timezone||!form.monthly_hours||!form.subject_ids.length){setMessage("البيانات المطلوبة: الاسم، العمر، الدولة، الساعات الشهرية، ومادة واحدة على الأقل.");return}setSaving(true);setMessage("");const {data:u}=await supabase.auth.getUser();if(!u.user){setMessage("انتهت جلسة الدخول.");setSaving(false);return}const payload={full_name:form.full_name.trim(),age:Number(form.age),country_code:form.country_code,timezone:form.timezone,native_language:form.native_language.trim()||null,contact_name:form.contact_name.trim()||null,contact_email:form.contact_email.trim()||null,contact_phone:form.contact_phone.trim()||null,monthly_hours:Number(form.monthly_hours),status:form.status,notes:form.notes.trim()||null,teacher_id:u.user.id};let id=editingId;if(editingId){const {error}=await supabase.from("students").update(payload).eq("id",editingId);if(error){setMessage(error.message);setSaving(false);return}await supabase.from("student_subjects").delete().eq("student_id",editingId)}else{const {data,error}=await supabase.from("students").insert(payload).select("id").single();if(error||!data){setMessage(error?.message||"تعذر حفظ الطالب.");setSaving(false);return}id=data.id}if(id){const {error}=await supabase.from("student_subjects").insert(form.subject_ids.map(subject_id=>({student_id:id,subject_id})));if(error){setMessage(error.message);setSaving(false);return}}await load();setFormOpen(false);setCountryPickerOpen(false);setSaving(false);setMessage(editingId?"تم تحديث بيانات الطالب.":"تمت إضافة الطالب بنجاح.")};
 const openDetails=async(s:Student)=>{setSelected(s);setDetailTab("overview");setDetailLoading(true);const [e,ss]=await Promise.all([supabase.from("events").select("starts_at,ends_at,title,status,is_makeup,notes,lesson_reports(taught_text,review_text,homework_text)").eq("student_id",s.id).order("starts_at",{ascending:false}).limit(50),supabase.from("student_subjects").select("subjects(id,name_ar,name_fr,name_en)").eq("student_id",s.id)]);setDetailLessons((e.data||[]) as DetailLesson[]);setDetailSubjects((ss.data||[]).map((r:any)=>r.subjects).filter(Boolean));setDetailLoading(false)};
 const archive=async(s:Student)=>{const next=s.status==="archived"?"active":"archived";const {error}=await supabase.from("students").update({status:next}).eq("id",s.id);if(!error){await load();setSelected(null);setMessage(next==="archived"?"تم أرشفة الطالب.":"تمت إعادة تفعيل الطالب.")}else setMessage(error.message)};
 const completed=detailLessons.filter(l=>l.status==="completed"),totalMins=detailLessons.reduce((n,l)=>n+duration(l.starts_at,l.ends_at),0);
 return <main className="students-page" dir="rtl">
  <header className="students-topbar"><div><p className="eyebrow">إدارة الطلاب</p><h1>الطلاب</h1><p className="subtitle">ملفات الطلاب، المواد، الساعات والتقدم في مكان واحد.</p></div><button className="primary-button" onClick={openCreate}><Plus size={17}/> إضافة طالب جديد</button></header>
  {message&&<div className="toast"><Check size={16}/><span>{message}</span><button onClick={()=>setMessage("")}><X size={15}/></button></div>}
  <section className="students-stats"><div><span className="stat-icon"><Users size={18}/></span><div><strong>{stats.total}</strong><small>إجمالي الطلاب</small></div></div><div><span className="stat-icon"><Check size={18}/></span><div><strong>{stats.active}</strong><small>طلاب نشطون</small></div></div><div><span className="stat-icon"><Clock3 size={18}/></span><div><strong>{stats.hours.toFixed(1)}</strong><small>ساعات مقررة / شهر</small></div></div><div><span className="stat-icon"><Archive size={18}/></span><div><strong>{stats.paused}</strong><small>متوقفون مؤقتًا</small></div></div></section>
  <section className="students-panel"><div className="panel-head"><div><span className="section-index">01</span><div><h2>قائمة الطلاب</h2><p>{filtered.length} طالب مطابق للبحث الحالي</p></div></div><div className="panel-tools"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الطالب أو ولي الأمر..."/></label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as any)}><option value="all">كل الحالات</option><option value="active">نشط</option><option value="paused">متوقف مؤقتًا</option><option value="archived">مؤرشف</option></select></div></div>
   {loading?<div className="empty-state"><div className="loading-mark">ر</div><p>جارٍ تحميل الطلاب...</p></div>:filtered.length===0?<div className="empty-state"><Users size={30}/><h3>لا يوجد طلاب مطابقون</h3><p>أضف طالبًا جديدًا أو عدّل البحث.</p></div>:<div className="student-list">{filtered.map(s=><article className="student-row" key={s.id}><div className="student-main"><div className="student-avatar">{initials(s.full_name)}</div><div><h3><span className="student-country-flag">{countryFlag(s.country_code)}</span>{s.full_name}</h3><p>{s.age?`${s.age} سنة`:"العمر غير محدد"} · {countryByCode(s.country_code||"")?.nameAr||s.country_code||"الدولة غير محددة"}</p></div></div><div className="student-cell subjects-cell"><span>المواد</span><div className="mini-subjects"><BookOpenCheck size={14}/><span>فتح ملف الطالب</span></div></div><div className="student-cell"><span>الساعات الشهرية</span><strong>{Number(s.monthly_hours).toFixed(1)} ساعة</strong></div><div className="student-cell"><span>المنطقة الزمنية</span><strong>{s.timezone.replace(/^.*\//,"").replaceAll("_"," ")}</strong></div><div className="student-status"><span className={`status-badge ${s.status}`}>{statusLabel[s.status]}</span><small>منذ {formatDate(s.created_at)}</small></div><div className="student-actions"><button onClick={()=>openDetails(s)} aria-label={`فتح ملف ${s.full_name}`}><ChevronLeft size={17}/></button><button onClick={()=>openEdit(s)} aria-label={`تعديل ${s.full_name}`}><Pencil size={16}/></button></div></article>)}</div>}
  </section>
  <section className="students-guide"><div><span className="guide-icon"><FileText size={19}/></span><div><strong>كشف الطالب قابل للطباعة والإرسال</strong><p>كشف متابعة تعليمي بالدروس والساعات والإنجازات، بدون مستحقات أو بيانات مالية.</p></div></div><span className="guide-note">مناسب للإرسال لولي الأمر</span></section>

  {formOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setFormOpen(false)}><section className="student-modal form-modal student-form-modal"><header><div><span className="section-index">02</span><div><h2>{editingId?"تعديل بيانات الطالب":"إضافة طالب جديد"}</h2><p>البيانات الأساسية للطالب، مع اختيار الدولة بسرعة.</p></div></div><button className="close-button" type="button" onClick={()=>setFormOpen(false)}><X size={18}/></button></header><form onSubmit={saveStudent}>
   <div className="form-grid">
    <label>اسم الطالب <em>*</em><input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="مثال: هارون"/></label>
    <label>العمر <em>*</em><input required type="number" min="1" max="100" value={form.age} onChange={e=>setForm({...form,age:e.target.value})} placeholder="12"/></label>
    <label className="country-field">الدولة <em>*</em><div className="country-picker"><button type="button" className={`country-trigger ${countryPickerOpen?"open":""}`} onClick={()=>setCountryPickerOpen(v=>!v)}><Globe2 size={17}/><span>{form.country_code?`${countryFlag(form.country_code)} ${countryByCode(form.country_code)?.nameAr||form.country_code}`:"اختر الدولة"}</span><ChevronLeft size={16}/></button>{countryPickerOpen&&<div className="country-menu"><div className="country-menu-head"><div><strong>{popularCountries.length?"الدول المستخدمة":"اختر دولة"}</strong><small>{popularCountries.length?"حتى ١٠ دول بها طلاب حاليًا":"لا توجد دول محفوظة بعد"}</small></div><button type="button" className="country-add-link" onClick={()=>{setAddCountryOpen(true);setAddCountryQuery("")}}><Plus size={15}/> إضافة دولة</button></div><label className="country-search"><Search size={15}/><input autoFocus value={countryQuery} onChange={e=>setCountryQuery(e.target.value)} placeholder="ابحث عن دولة..."/><span>{countryQuery?searchedCountries.length:popularCountries.length}</span></label><div className="country-options">{searchedCountries.map(c=><button type="button" key={c.code} className={`country-option ${c.code===form.country_code?"selected":""}`} onClick={()=>selectCountry(c.code)}><span><span className="country-option-flag">{countryFlag(c.code)}</span>{c.nameAr}</span><small>{c.code}</small></button>)}{!searchedCountries.length&&<div className="country-no-results">لا توجد نتيجة. استخدم «إضافة دولة» للبحث في كل الدول.</div>}</div></div>}</div></label>
    <label>المنطقة الزمنية <em>*</em><div className="timezone-control"><input readOnly value={form.timezone} placeholder="تظهر تلقائيًا"/><span>{form.country_code?"تم التعرف عليها تلقائيًا من الدولة":"اختر الدولة أولًا"}</span></div></label>
    <label>اللغة الأم<input value={form.native_language} onChange={e=>setForm({...form,native_language:e.target.value})} placeholder="فرنسية / هولندية..."/></label>
    <label>الساعات الشهرية <em>*</em><input required type="number" min="0.5" step="0.5" value={form.monthly_hours} onChange={e=>setForm({...form,monthly_hours:e.target.value})}/></label>
    <label>اسم ولي الأمر<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></label>
    <label>هاتف ولي الأمر<input dir="ltr" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></label>
    <label>بريد ولي الأمر<input dir="ltr" type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label>
    <label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as FormState["status"]})}><option value="active">نشط</option><option value="paused">متوقف مؤقتًا</option><option value="archived">مؤرشف</option></select></label>
   </div>
   <div className="form-section"><div><h3>المواد الدراسية <em>*</em></h3><p>اختر مادة واحدة أو أكثر.</p></div><div className="subject-picker">{subjects.map(sub=><button type="button" key={sub.id} className={form.subject_ids.includes(sub.id)?"selected":""} onClick={()=>setForm({...form,subject_ids:form.subject_ids.includes(sub.id)?form.subject_ids.filter(id=>id!==sub.id):[...form.subject_ids,sub.id]})}>{sub.name_ar}{form.subject_ids.includes(sub.id)&&<Check size={14}/>}</button>)}</div></div>
   <label className="full-field">ملاحظات<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات عامة عن الطالب..."/></label>
   <footer><button type="button" className="secondary-button" onClick={()=>setFormOpen(false)}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?"جارٍ الحفظ...":editingId?"حفظ التعديلات":"إضافة الطالب"}</button></footer>
  </form></section></div>}

  {addCountryOpen&&<div className="modal-backdrop country-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!addingCountry&&setAddCountryOpen(false)}><section className="student-modal country-modal country-directory-modal"><header><div><span className="section-index">03</span><div><h2>إضافة دولة</h2><p>ابحث باسم الدولة واخترها. سيتم حفظها تلقائيًا واكتشاف المنطقة الزمنية.</p></div></div><button className="close-button" type="button" disabled={addingCountry} onClick={()=>setAddCountryOpen(false)}><X size={18}/></button></header><div className="country-directory-body"><label className="country-search country-directory-search"><Search size={16}/><input autoFocus value={addCountryQuery} onChange={e=>setAddCountryQuery(e.target.value)} placeholder="ابحث باسم الدولة أو بالإنجليزية أو ISO..."/><span>{allCountriesForAdd.length}</span></label><div className="country-directory-list">{allCountriesForAdd.map(c=><button type="button" key={c.code} className="country-directory-option" disabled={addingCountry} onClick={()=>addCountryFromDirectory(c.code)}><span><span className="country-option-flag">{countryFlag(c.code)}</span><strong>{c.nameAr}</strong><small>{c.nameEn}</small></span><b>{c.code}</b></button>)}</div></div></section></div>}

  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="student-modal detail-modal"><header><div className="detail-heading"><div className="student-avatar large">{initials(selected.full_name)}</div><div><span className={`status-badge ${selected.status}`}>{statusLabel[selected.status]}</span><h2><span className="student-country-flag">{countryFlag(selected.country_code)}</span>{selected.full_name}</h2><p>{selected.age?`${selected.age} سنة`:"العمر غير محدد"} · {countryByCode(selected.country_code||"")?.nameAr||selected.country_code||"الدولة غير محددة"} · {selected.timezone}</p></div></div><button className="close-button" type="button" onClick={()=>setSelected(null)}><X size={18}/></button></header><div className="detail-tabs"><button className={detailTab==="overview"?"active":""} onClick={()=>setDetailTab("overview")}>نظرة عامة</button><button className={detailTab==="lessons"?"active":""} onClick={()=>setDetailTab("lessons")}>الحصص</button><button className={detailTab==="statement"?"active":""} onClick={()=>setDetailTab("statement")}>كشف المتابعة</button></div>{detailLoading?<div className="empty-state compact"><div className="loading-mark">ر</div><p>جارٍ تحميل ملف الطالب...</p></div>:<>
   {detailTab==="overview"&&<div className="detail-content"><div className="info-grid"><div><span><Clock3 size={15}/> الساعات الشهرية</span><strong>{Number(selected.monthly_hours).toFixed(1)} ساعة</strong></div><div><span><Globe2 size={15}/> المنطقة الزمنية</span><strong>{selected.timezone}</strong></div><div><span><MapPin size={15}/> الدولة</span><strong><span className="student-country-flag">{countryFlag(selected.country_code)}</span>{countryByCode(selected.country_code||"")?.nameAr||selected.country_code||"غير محددة"}</strong></div><div><span><UserRound size={15}/> اللغة الأم</span><strong>{selected.native_language||"غير محددة"}</strong></div></div><div className="detail-columns"><div className="detail-card"><div className="card-title"><h3>المواد الدراسية</h3><span>{detailSubjects.length}</span></div><div className="subject-chips">{detailSubjects.map(s=><span key={s.id}><BookOpenCheck size={13}/>{s.name_ar}</span>)}</div></div><div className="detail-card"><div className="card-title"><h3>بيانات ولي الأمر</h3></div><div className="contact-list">{selected.contact_name&&<span><UserRound size={14}/>{selected.contact_name}</span>}{selected.contact_email&&<span dir="ltr"><Mail size={14}/>{selected.contact_email}</span>}{selected.contact_phone&&<span dir="ltr"><Phone size={14}/>{selected.contact_phone}</span>}{!selected.contact_name&&!selected.contact_email&&!selected.contact_phone&&<p className="muted">لا توجد بيانات اتصال.</p>}</div></div></div><div className="detail-card notes-card"><div className="card-title"><h3>ملاحظات المعلم</h3></div><p>{selected.notes||"لا توجد ملاحظات مسجلة."}</p></div><div className="detail-footer"><div><span className="guide-note">إدارة حالة الطالب</span></div><div><button className="secondary-button" onClick={()=>openEdit(selected)}><Pencil size={15}/> تعديل</button><button className="danger-button" onClick={()=>archive(selected)}>{selected.status==="archived"?"إعادة تفعيل":"أرشفة"}</button></div></div></div>}
   {detailTab==="lessons"&&<div className="detail-content"><div className="mini-stats"><div><strong>{detailLessons.length}</strong><span>إجمالي الحصص</span></div><div><strong>{completed.length}</strong><span>مكتملة</span></div><div><strong>{(totalMins/60).toFixed(1)}</strong><span>ساعة مسجلة</span></div></div><div className="lesson-list">{detailLessons.length?detailLessons.map((l,i)=><div className="lesson-item" key={`${l.starts_at}-${i}`}><div className="lesson-time"><strong>{formatTime(l.starts_at)}</strong><span>{formatDate(l.starts_at)}</span></div><div className="lesson-body"><h3>{l.title}</h3><p>{l.lesson_reports?.[0]?.taught_text||l.notes||"لا يوجد وصف للحصة بعد."}</p></div><span className={`lesson-status ${l.status}`}>{l.status==="completed"?"مكتملة":l.is_makeup?"تعويضية":"مجدولة"}</span></div>):<div className="empty-state compact"><CalendarDays size={28}/><p>لا توجد حصص مسجلة لهذا الطالب حتى الآن.</p></div>}</div></div>}
   {detailTab==="statement"&&<div className="statement-wrap"><div className="statement-head"><div><span>رواق · إدارة التعليم</span><h2><span className="student-country-flag">{countryFlag(selected.country_code)}</span>كشف متابعة الطالب</h2><p>كشف تعليمي قابل للمشاركة مع ولي الأمر ولا يتضمن أي مستحقات أو بيانات مالية.</p></div><button className="secondary-button no-print" onClick={()=>window.print()}><FileText size={15}/> طباعة / PDF</button></div><div className="statement-student"><div><span>الطالب</span><strong><span className="student-country-flag">{countryFlag(selected.country_code)}</span>{selected.full_name}</strong></div><div><span>الساعات الشهرية</span><strong>{Number(selected.monthly_hours).toFixed(1)} ساعة</strong></div><div><span>الحصص المكتملة</span><strong>{completed.length}</strong></div><div><span>الساعات المسجلة</span><strong>{(totalMins/60).toFixed(1)} ساعة</strong></div></div><div className="statement-table"><div className="table-row table-head"><span>التاريخ</span><span>الحصة</span><span>المدة</span><span>الإنجاز / التقرير</span></div>{completed.length?completed.slice(0,20).map((l,i)=><div className="table-row" key={`${l.starts_at}-${i}`}><span>{formatDate(l.starts_at)}</span><span>{l.title}</span><span>{duration(l.starts_at,l.ends_at)} د</span><span>{l.lesson_reports?.[0]?.taught_text||l.lesson_reports?.[0]?.review_text||"تمت الحصة بنجاح."}</span></div>):<div className="statement-empty">لا توجد حصص مكتملة مسجلة حتى الآن.</div>}</div><div className="statement-footer">رواق · تقرير متابعة تعليمي — بدون مستحقات مالية</div></div>}
  </>}</section></div>}
 </main>
}
