"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, Clock3, FileText, Globe2, Pencil, Phone, Plus, Search, Star, Trash2, UserRound, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { countryFlag } from "../../lib/country";
import "./students-reference.css";

type Student={id:string;full_name:string;age:number|null;country_code:string|null;timezone:string;native_language:string|null;contact_email:string|null;contact_phone:string|null;compensation_type:string;currency_code:string|null;center_name:string|null;center_number:string|null;monthly_hours:number;status:string;notes:string|null};
type Lesson={id:string;student_id:string;starts_at:string;ends_at:string;status:string;notes:string|null;title:string};
const now=new Date();
const pad=(n:number)=>String(n).padStart(2,"0");
const isoDate=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;

export default function StudentsReference(){
 const [students,setStudents]=useState<Student[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState("");
 const [studentModal,setStudentModal]=useState(false),[editing,setEditing]=useState<Student|null>(null),[lessonModal,setLessonModal]=useState(false),[lessonStudent,setLessonStudent]=useState<Student|null>(null),[message,setMessage]=useState("");
 const [studentForm,setStudentForm]=useState({full_name:"",age:"",country_code:"",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,native_language:"",contact_phone:"",monthly_hours:"8",compensation_type:"virtual_currency",currency_code:"EUR",center_name:"",center_number:"",status:"active",notes:""});
 const [lessonForm,setLessonForm]=useState({date:isoDate(),time:"16:00",minutes:"60",status:"completed",rating:5,learned:"",report:"",homework:""});
 const load=async()=>{setLoading(true);const start=new Date(now.getFullYear(),now.getMonth(),1).toISOString();const end=new Date(now.getFullYear(),now.getMonth()+1,1).toISOString();const [s,e]=await Promise.all([supabase.from("students").select("*").order("created_at",{ascending:false}),supabase.from("events").select("id,student_id,starts_at,ends_at,status,notes,title").eq("event_type","lesson").gte("starts_at",start).lt("starts_at",end).order("starts_at",{ascending:false})]);if(s.error)setMessage(s.error.message);else setStudents((s.data||[]) as Student[]);if(!e.error)setLessons((e.data||[]) as Lesson[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const hours=useMemo(()=>{const out:Record<string,number>={};lessons.filter(l=>l.status==="completed").forEach(l=>out[l.student_id]=(out[l.student_id]||0)+Math.max(0,(new Date(l.ends_at).getTime()-new Date(l.starts_at).getTime())/3600000));return out},[lessons]);
 const filtered=students.filter(s=>`${s.full_name} ${s.country_code||""}`.toLowerCase().includes(query.toLowerCase()));
 const openStudent=(s?:Student)=>{setEditing(s||null);setStudentForm(s?{full_name:s.full_name,age:String(s.age||""),country_code:s.country_code||"",timezone:s.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,native_language:s.native_language||"",contact_phone:s.contact_phone||"",monthly_hours:String(s.monthly_hours||8),compensation_type:s.compensation_type||"virtual_currency",currency_code:s.currency_code||"EUR",center_name:s.center_name||"",center_number:s.center_number||"",status:s.status||"active",notes:s.notes||""}:{full_name:"",age:"",country_code:"",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,native_language:"",contact_phone:"",monthly_hours:"8",compensation_type:"virtual_currency",currency_code:"EUR",center_name:"",center_number:"",status:"active",notes:""});setStudentModal(true)};
 const saveStudent=async(e:FormEvent)=>{e.preventDefault();if(!studentForm.full_name.trim()){setMessage("اكتب اسم الطالب أولًا.");return}const {data:user}=await supabase.auth.getUser();if(!user.user){setMessage("انتهت جلسة الدخول.");return}const payload={...studentForm,full_name:studentForm.full_name.trim(),age:studentForm.age?Number(studentForm.age):null,monthly_hours:Number(studentForm.monthly_hours||8),teacher_id:user.user.id,notes:studentForm.notes||null};const r=editing?await supabase.from("students").update(payload).eq("id",editing.id):await supabase.from("students").insert(payload);if(r.error){setMessage(r.error.message);return}setStudentModal(false);await load();setMessage(editing?"تم تحديث الطالب.":"تمت إضافة الطالب.")};
 const remove=async(s:Student)=>{if(!confirm(`حذف ${s.full_name}؟`))return;const {error}=await supabase.from("students").update({status:"archived"}).eq("id",s.id);if(error)setMessage(error.message);else{await load();setMessage("تمت أرشفة الطالب.")}};
 const openLesson=(s:Student)=>{setLessonStudent(s);setLessonForm({date:isoDate(),time:new Date().toTimeString().slice(0,5),minutes:"60",status:"completed",rating:5,learned:"",report:"",homework:""});setLessonModal(true)};
 const saveLesson=async(e:FormEvent)=>{e.preventDefault();if(!lessonStudent)return;const start=new Date(`${lessonForm.date}T${lessonForm.time}:00`);if(Number.isNaN(start.getTime())){setMessage("راجع تاريخ ووقت الحصة.");return}const end=new Date(start.getTime()+Number(lessonForm.minutes||60)*60000);const {data:user}=await supabase.auth.getUser();if(!user.user){setMessage("انتهت جلسة الدخول.");return}const notes=JSON.stringify({rating:lessonForm.rating,learned:lessonForm.learned,report:lessonForm.report,homework:lessonForm.homework});const {error}=await supabase.from("events").insert({student_id:lessonStudent.id,teacher_id:user.user.id,event_type:"lesson",title:`حصة ${lessonStudent.full_name}`,starts_at:start.toISOString(),ends_at:end.toISOString(),timezone:lessonStudent.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,status:lessonForm.status,is_makeup:false,reminder_minutes:0,notes});if(error){setMessage(error.message);return}setLessonModal(false);await load();const total=(hours[lessonStudent.id]||0)+Number(lessonForm.minutes)/60;if(total>=Number(lessonStudent.monthly_hours||0)){setMessage(`${lessonStudent.full_name} أكمل ساعاته الشهرية${lessonStudent.compensation_type==="center"?" — أصبح تقرير المركز جاهزًا من بطاقة الطالب.":"."}`)}else setMessage("تم تسجيل الحصة بنجاح.")};
 const printStatement=(s:Student)=>{const done=(hours[s.id]||0).toFixed(1);const html=`<html dir="rtl"><head><title>كشف حساب الطالب</title><style>body{font-family:Arial;padding:40px;color:#27352d}h1{color:#526a58;border-bottom:2px solid #526a58;padding-bottom:12px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:24px}.box{border:1px solid #ddd;padding:14px;border-radius:10px}</style></head><body><h1>رواق — كشف حساب الطالب</h1><div class="grid"><div class="box"><b>الطالب:</b> ${s.full_name}</div><div class="box"><b>الساعات المنجزة:</b> ${done} ساعة</div><div class="box"><b>الساعات المقررة:</b> ${s.monthly_hours} ساعة</div><div class="box"><b>الفترة:</b> ${now.toLocaleDateString("ar-EG",{month:"long",year:"numeric"})}</div></div><script>print()</script></body></html>`;const w=window.open("","_blank");if(w){w.document.write(html);w.document.close()}};
 return <main className="students-ref-page" dir="rtl"><section className="students-ref-hero"><div><h1>سجل بيانات الطلاب <span>{students.length} طالبًا مسجلًا</span></h1><p>إدارة بيانات الطلاب، المناطق الزمنية، المناهج، العملة الافتراضية والتواصل المباشر.</p></div><div className="students-ref-actions"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالاسم أو الدولة..."/></label><button onClick={()=>openStudent()}><Plus size={17}/> تسجيل طالب جديد</button></div></section>
 <section className="students-ref-grid">{loading?<p>جارٍ تحميل الطلاب...</p>:filtered.map(s=>{const done=hours[s.id]||0,goal=Number(s.monthly_hours||0),pct=goal?Math.min(100,done/goal*100):0,complete=done>=goal&&goal>0;return <article className={`student-ref-card ${complete?"complete":""}`} key={s.id}><header><div className="card-edit"><button onClick={()=>openStudent(s)}><Pencil size={15}/></button><button onClick={()=>remove(s)}><Trash2 size={15}/></button></div><div><h2>{countryFlag(s.country_code||"")} {s.full_name}</h2><p>{s.country_code||"—"} · {s.native_language||"طالب"} · {s.status==="active"?"منتظم":"متوقف"}</p></div></header><div className="student-ref-rate"><span>{s.currency_code||"USD"} {s.compensation_type==="center"?"مركز":s.monthly_hours}</span><b>الأجر الدراسي:</b></div><div className="student-ref-subject"><BookOpen size={14}/><span>{s.notes||"لم يتم تحديد وصف الدراسة بعد"}</span></div><div className="student-ref-meta"><span><Globe2 size={14}/> المنطقة الزمنية: {s.timezone||"حسب الطالب"}</span><span><Phone size={14}/> {s.contact_phone||"لا يوجد رقم مسجل"}</span></div><div className="student-ref-hours"><div><b>ساعات هذا الشهر:</b><strong>{done.toFixed(1)} / {goal} ساعة</strong></div><div className="hours-line"><i style={{width:`${pct}%`}}/></div><small>{complete?"✓ اكتملت الساعات الشهرية":`محسوب منفذ ${pct.toFixed(0)}% من الهدف`}</small></div><footer><button className="record" onClick={()=>openLesson(s)}><Plus size={14}/> تسجيل حصة</button><button onClick={()=>printStatement(s)}><FileText size={14}/> كشف حساب</button>{s.compensation_type==="center"&&complete&&<button onClick={()=>setMessage(`تقرير المركز: ${s.full_name} — ${s.center_name||"—"} — ${s.center_number||"—"}`)}><FileText size={14}/> تقرير مركز</button>}</footer></article>})}</section>
 {studentModal&&<div className="student-ref-backdrop"><form className="student-ref-modal" onSubmit={saveStudent}><header><div><UserRound size={18}/><h2>{editing?"تعديل بيانات الطالب":"تسجيل طالب جديد"}</h2></div><button type="button" onClick={()=>setStudentModal(false)}><X size={19}/></button></header><div className="student-ref-form"><label>اسم الطالب<input value={studentForm.full_name} onChange={e=>setStudentForm({...studentForm,full_name:e.target.value})}/></label><label>العمر<input type="number" value={studentForm.age} onChange={e=>setStudentForm({...studentForm,age:e.target.value})}/></label><label>الدولة<input value={studentForm.country_code} onChange={e=>setStudentForm({...studentForm,country_code:e.target.value.toUpperCase()})} placeholder="مثال: BE"/></label><label>المنطقة الزمنية<input value={studentForm.timezone} onChange={e=>setStudentForm({...studentForm,timezone:e.target.value})}/></label><label>اللغة الأم<input value={studentForm.native_language} onChange={e=>setStudentForm({...studentForm,native_language:e.target.value})}/></label><label>رقم التواصل<input value={studentForm.contact_phone} onChange={e=>setStudentForm({...studentForm,contact_phone:e.target.value})}/></label><label>الساعات الشهرية<input type="number" value={studentForm.monthly_hours} onChange={e=>setStudentForm({...studentForm,monthly_hours:e.target.value})}/></label><label>نوع الحساب<select value={studentForm.compensation_type} onChange={e=>setStudentForm({...studentForm,compensation_type:e.target.value})}><option value="virtual_currency">عملة افتراضية</option><option value="center">مركز</option></select></label>{studentForm.compensation_type==="center"&&<><label>اسم المركز<input value={studentForm.center_name} onChange={e=>setStudentForm({...studentForm,center_name:e.target.value})}/></label><label>رقم المركز<input value={studentForm.center_number} onChange={e=>setStudentForm({...studentForm,center_number:e.target.value})}/></label></>}<label className="wide">ملاحظات الدراسة<textarea value={studentForm.notes} onChange={e=>setStudentForm({...studentForm,notes:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setStudentModal(false)}>إلغاء</button><button className="save" type="submit"><CheckCircle2 size={16}/> حفظ الطالب</button></footer></form></div>}
 {lessonModal&&<div className="student-ref-backdrop lesson-backdrop"><form className="lesson-ref-modal" onSubmit={saveLesson}><header><button type="button" onClick={()=>setLessonModal(false)}><X size={20}/></button><h2><CheckCircle2 size={20}/> تسجيل إنجاز وساعات حصة جديدة</h2></header><div className="lesson-body"><label className="lesson-wide">الطالب<select value={lessonStudent?.id||""} disabled><option>{lessonStudent?.full_name}</option></select></label><div className="lesson-row"><label>تاريخ الحصة<input type="date" value={lessonForm.date} onChange={e=>setLessonForm({...lessonForm,date:e.target.value})}/></label><label>وقت البدء<input type="time" value={lessonForm.time} onChange={e=>setLessonForm({...lessonForm,time:e.target.value})}/></label><label>المدة المستغرقة<select value={lessonForm.minutes} onChange={e=>setLessonForm({...lessonForm,minutes:e.target.value})}><option value="30">30 دقيقة</option><option value="45">45 دقيقة</option><option value="60">60 دقيقة (1 ساعة)</option><option value="90">90 دقيقة</option><option value="120">120 دقيقة</option></select></label></div><div className="lesson-row lesson-status-row"><label className="wide-row">حالة الحصة<select value={lessonForm.status} onChange={e=>setLessonForm({...lessonForm,status:e.target.value})}><option value="completed">تمت الحصة بنجاح</option><option value="cancelled">ألغيت</option><option value="missed">لم يحضر الطالب</option></select></label><div className="rating"><span>تقييم أداء الطالب ونسبته:</span><div>{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=lessonForm.rating?"on":""} onClick={()=>setLessonForm({...lessonForm,rating:n})}><Star size={20} fill="currentColor"/></button>)}</div></div></div><label className="lesson-wide">ماذا درس الطالب أو أتقنه؟<input value={lessonForm.learned} onChange={e=>setLessonForm({...lessonForm,learned:e.target.value})} placeholder="مثال: حفظ سورة النساء + مراجعة الجزء الأول + تدريب أحكام النون والتنوين"/></label><label className="lesson-wide">ما تم إنجازه وتقييمه خلال الحصة<textarea value={lessonForm.report} onChange={e=>setLessonForm({...lessonForm,report:e.target.value})} placeholder="مثال: تم تسميع الآيات 1–35 من سورة النساء مع مراجعة أحكام الإخفاء الحقيقي..."/></label><label className="lesson-wide">الواجب والتكليفات المطلوبة للحصة القادمة<input value={lessonForm.homework} onChange={e=>setLessonForm({...lessonForm,homework:e.target.value})} placeholder="مثال: حفظ الآيات 36–50 + مراجعة 5 أوجه من البقرة"/></label></div><footer><button type="submit" className="save-lesson"><CheckCircle2 size={16}/> حفظ سجل الحصة</button><button type="button" onClick={()=>setLessonModal(false)}>إلغاء</button></footer></form></div>}
 {message&&<div className="student-ref-toast">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 </main>
}
