"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, FileText, Plus, Users, WalletCards } from "lucide-react";
import AppShell from "../../components/app-shell";
import { getEvents, getStudents } from "../../lib/data";
import { supabase } from "../../lib/supabase";
import { formatInTimeZone, formatTimeInZone } from "../../lib/timezone";

type Student = { id:string; full_name:string; age:number|null; country_code:string|null; timezone:string; monthly_hours:number; status:string };
type Event = { id:string; student_id:string|null; event_type:string; title:string; starts_at:string; ends_at:string; timezone:string; status:string; is_makeup:boolean; students?:{full_name:string}|null };
type AlertItem={kind:"homework"|"payment"|"report";text:string};

export default function DashboardPage(){
 const [students,setStudents]=useState<Student[]>([]),[events,setEvents]=useState<Event[]>([]),[alerts,setAlerts]=useState<AlertItem[]>([]),[loading,setLoading]=useState(true);
 async function load(){try{const s=await getStudents();const now=new Date(),to=new Date(now);to.setDate(to.getDate()+30);const e=await getEvents(now.toISOString(),to.toISOString());if(!s.error)setStudents((s.data||[]) as Student[]);if(!e.error)setEvents((e.data||[]) as Event[]);if(supabase){const [h,p,r]=await Promise.all([supabase.from("homework").select("id,title,students(full_name)").eq("status","pending"),supabase.from("payments").select("id,amount_due,amount_paid,students(full_name)").eq("teacher_id",(s.data?.[0] as any)?.teacher_id||"") ,supabase.from("events").select("id,title,students(full_name)").eq("event_type","lesson").eq("status","completed")]);const a:AlertItem[]=[];(h.data||[]).slice(0,5).forEach((x:any)=>a.push({kind:"homework",text:`واجب غير مكتمل: ${x.students?.full_name||x.title}`}));(p.data||[]).filter((x:any)=>Number(x.amount_due||0)>Number(x.amount_paid||0)).slice(0,5).forEach((x:any)=>a.push({kind:"payment",text:`مستحق غير مكتمل: ${x.students?.full_name||"طالب"}`}));const reportEvents=new Set<string>();if(r.data){const doneReports=await supabase.from("lesson_reports").select("event_id").in("event_id",r.data.map((x:any)=>x.id));(doneReports.data||[]).forEach((x:any)=>reportEvents.add(x.event_id));(r.data as any[]).filter(x=>!reportEvents.has(x.id)).slice(0,5).forEach(x=>a.push({kind:"report",text:`تقرير ناقص: ${x.students?.full_name||x.title}`}))}setAlerts(a.slice(0,8));}}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const active=students.filter(s=>s.status==="active").length;
 const upcoming=events.filter(e=>e.status==="scheduled").slice(0,6);
 const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),monthEnd=new Date(now.getFullYear(),now.getMonth()+1,1);
 const monthEvents=events.filter(e=>new Date(e.starts_at)>=monthStart&&new Date(e.starts_at)<monthEnd&&e.event_type==="lesson");
 const planned=monthEvents.reduce((n,e)=>n+Math.max(0,(new Date(e.ends_at).getTime()-new Date(e.starts_at).getTime())/3600000),0);
 const completed=monthEvents.filter(e=>e.status==="completed").reduce((n,e)=>n+Math.max(0,(new Date(e.ends_at).getTime()-new Date(e.starts_at).getTime())/3600000),0);
 return <AppShell><section className="hero"><div><p className="eyebrow">لوحة التحكم</p><h2>نظرة سريعة على التدريس اليوم.</h2><p>الطلاب والحصص والساعات والتنبيهات والإجراءات المهمة في شاشة واحدة.</p></div><div className="top-actions"><Link className="outline-btn" href="/calendar"><CalendarDays size={16}/> التقويم</Link><Link className="primary-btn" href="/calendar?action=new"><Plus size={16}/> إضافة موعد</Link></div></section>
 <section className="grid4"><Stat icon={<Users size={17}/>} label="الطلاب النشطون" value={loading?"…":active}/><Stat icon={<CalendarDays size={17}/>} label="الحصص القادمة" value={loading?"…":upcoming.length}/><Stat icon={<Clock3 size={17}/>} label="الساعات المخططة هذا الشهر" value={loading?"…":`${planned.toFixed(1)} ساعة`}/><Stat icon={<CheckCircle2 size={17}/>} label="الساعات المنفذة" value={loading?"…":`${completed.toFixed(1)} ساعة`}/></section>
 <div className="dashboard-grid"><section className="card"><div className="section-title"><b>الحصص القادمة</b><Link href="/calendar">عرض الكل</Link></div>{upcoming.length?upcoming.map(e=><div className="calendar-event" key={e.id}><div className="cal-time">{formatTimeInZone(e.starts_at,e.timezone)}</div><div className="cal-line"><span/></div><div className="cal-body"><b>{e.students?.full_name||e.title}</b><span>{e.title} · {formatInTimeZone(e.starts_at,e.timezone)}</span></div><span className="pill">{e.is_makeup?"تعويض":"حصة"}</span></div>):<div className="empty"><div className="empty-icon"><CalendarDays size={22}/></div><h2>لا توجد حصص قادمة</h2><p>أضف أول موعد من صفحة التقويم.</p><Link className="primary-btn" href="/calendar?action=new">إضافة موعد</Link></div>}</section>
 <section className="card"><div className="section-title"><b>التنبيهات</b><Link href="/notifications">عرض الكل</Link></div>{alerts.length?alerts.map((a,i)=><div className="notice" key={i}><div className="notice-icon">{a.kind==="payment"?<WalletCards size={15}/>:a.kind==="report"?<FileText size={15}/>:<AlertTriangle size={15}/>}</div><span>{a.text}</span></div>):<div className="empty"><CheckCircle2 size={25}/><h3>كل شيء تحت السيطرة</h3><p>لا توجد تنبيهات معلقة حاليًا.</p></div>}</section></div>
 <section className="card"><div className="section-title"><b>الطلاب النشطون</b><Link href="/students">إدارة الطلاب</Link></div>{students.filter(s=>s.status==="active").slice(0,6).map(s=><div className="student-row" key={s.id}><div className="avatar">{s.full_name[0]}</div><div className="student-info"><b>{s.full_name}</b><span>{s.age?`${s.age} سنة`:"العمر غير محدد"} · {s.timezone}</span></div></div>)}</section></AppShell>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="card stat"><div className="stat-icon">{icon}</div><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>}
