"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { AlertTriangle,ArrowLeft,CalendarDays,CheckCircle2,Clock3,FileText,Plus,Users,WalletCards } from "lucide-react";
import AppShell from "../../components/app-shell";
import { getEvents,getStudents } from "../../lib/data";
import { supabase } from "../../lib/supabase";
import { requireTeacherId } from "../../lib/current-teacher";
import { formatInTimeZone,formatTimeInZone } from "../../lib/timezone";
import { syncRecurringSchedules } from "../../lib/recurring";
import "./dashboard.css";

type Student={id:string;full_name:string;age:number|null;country_code?:string|null;timezone:string;monthly_hours?:number;status:string};
type Event={id:string;student_id:string|null;event_type:string;title:string;starts_at:string;ends_at:string;timezone:string;status:string;is_makeup?:boolean;students?:{full_name:string}|null};
type AlertItem={kind:"homework"|"payment"|"report";text:string};
const dateKey=(v:string,tz:string)=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:tz||"UTC",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(v));const g=(x:string)=>p.find(a=>a.type===x)?.value||"";return `${g("year")}-${g("month")}-${g("day")}`};
const eventState=(e:Event)=>{const n=Date.now(),s=+new Date(e.starts_at),x=+new Date(e.ends_at);if(e.status==="completed"||x<n)return ["انتهت","status-done"];if(s<=n&&n<=x)return ["جارٍ الآن","status-live"];return ["قادمة","status-next"]};
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string|number;detail?:string}){return <div className="card dashboard-stat"><div className="dashboard-stat-top"><div className="dashboard-stat-icon">{icon}</div>{detail&&<span className="pill">{detail}</span>}</div><div className="dashboard-stat-label">{label}</div><div className="dashboard-stat-value">{value}</div></div>}
export default function DashboardPage(){
 const [students,setStudents]=useState<Student[]>([]),[events,setEvents]=useState<Event[]>([]),[alerts,setAlerts]=useState<AlertItem[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const teacher=await requireTeacherId();await syncRecurringSchedules(90);const now=new Date();const [s,e]=await Promise.all([getStudents(),getEvents(new Date(now.getFullYear(),now.getMonth(),1).toISOString(),new Date(now.getFullYear(),now.getMonth()+2,1).toISOString())]);if(!s.error)setStudents((s.data||[]) as Student[]);if(!e.error)setEvents((e.data||[]) as Event[]);if(supabase){const [h,p,r]=await Promise.all([supabase.from("homework").select("id,title,students(full_name)").eq("teacher_id",teacher).eq("status","pending"),supabase.from("payments").select("id,amount_due,amount_paid,students(full_name)").eq("teacher_id",teacher),supabase.from("events").select("id,title,students(full_name)").eq("teacher_id",teacher).eq("event_type","lesson").eq("status","completed").gte("starts_at",new Date(Date.now()-30*86400000).toISOString())]);const a:AlertItem[]=[];(h.data||[]).slice(0,4).forEach((x:any)=>a.push({kind:"homework",text:`واجب غير مكتمل: ${x.students?.full_name||x.title}`}));(p.data||[]).filter((x:any)=>Number(x.amount_due||0)>Number(x.amount_paid||0)).slice(0,4).forEach((x:any)=>a.push({kind:"payment",text:`مستحق غير مكتمل: ${x.students?.full_name||"طالب"}`}));if(r.data?.length){const ids=r.data.map((x:any)=>x.id);const d=await supabase.from("lesson_reports").select("event_id").eq("teacher_id",teacher).in("event_id",ids);const done=new Set((d.data||[]).map((x:any)=>x.event_id));(r.data as any[]).filter(x=>!done.has(x.id)).slice(0,4).forEach(x=>a.push({kind:"report",text:`تقرير ناقص: ${x.students?.full_name||x.title}`}))}setAlerts(a.slice(0,8))}}finally{setLoading(false)}})()},[]);
 const now=new Date(),tz=Intl.DateTimeFormat().resolvedOptions().timeZone,todayKey=dateKey(now.toISOString(),tz),active=students.filter(s=>s.status==="active"),lessons=useMemo(()=>events.filter(e=>e.event_type==="lesson"&&e.status!=="cancelled"),[events]);
 const today=lessons.filter(e=>dateKey(e.starts_at,e.timezone)===todayKey).sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at));
 const upcoming=lessons.filter(e=>+new Date(e.starts_at)>=Date.now()).sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)).slice(0,6);
 const ms=new Date(now.getFullYear(),now.getMonth(),1),me=new Date(now.getFullYear(),now.getMonth()+1,1),month=lessons.filter(e=>new Date(e.starts_at)>=ms&&new Date(e.starts_at)<me),hours=(e:Event)=>Math.max(0,(+new Date(e.ends_at)-+new Date(e.starts_at))/36e5),planned=month.reduce((n,e)=>n+hours(e),0),completed=month.filter(e=>e.status==="completed").reduce((n,e)=>n+hours(e),0),progress=planned?Math.min(100,completed/planned*100):0;
 const dateLabel=now.toLocaleDateString("ar-EG",{weekday:"long",day:"numeric",month:"long"});
 return <AppShell><main className="dashboard-page">
  <section className="riwaq-hero"><div className="riwaq-hero-glow"/><div className="riwaq-hero-content"><div className="riwaq-eyebrow">لوحة التحكم</div><h1>{dateLabel}</h1><p>نظرة واحدة على حصصك وطلابك وما يحتاج انتباهك اليوم.</p></div><div className="riwaq-hero-actions"><Link href="/students?action=new" className="riwaq-light-btn"><Plus size={16}/> طالب جديد</Link><Link href="/calendar-riwaq?action=new" className="riwaq-dark-btn"><CalendarDays size={16}/> إضافة موعد</Link></div></section>
  <section className="dashboard-stats"><Stat icon={<Users size={18}/>} label="الطلاب النشطون" value={loading?"…":active.length}/><Stat icon={<CalendarDays size={18}/>} label="حصص اليوم" value={loading?"…":today.length}/><Stat icon={<Clock3 size={18}/>} label="الساعات المخططة" value={loading?"…":`${planned.toFixed(1)} ساعة`} detail="هذا الشهر"/><Stat icon={<CheckCircle2 size={18}/>} label="الساعات المنفذة" value={loading?"…":`${completed.toFixed(1)} ساعة`} detail={`${Math.round(progress)}%`}/></section>
  <div className="riwaq-dashboard-grid"><section className="card riwaq-next-card"><div className="riwaq-section-head"><div><span className="riwaq-section-kicker"><CalendarDays size={14}/> الحصص القادمة</span><h2>حصصك القادمة</h2></div><Link className="riwaq-more" href="/calendar-riwaq">عرض التقويم <ArrowLeft size={14}/></Link></div>{upcoming.length?<div className="riwaq-timeline">{upcoming.map(e=>{const [label,cls]=eventState(e);return <div className="riwaq-timeline-item" key={e.id}><div className="riwaq-timeline-time">{formatTimeInZone(e.starts_at,e.timezone)}</div><div className="riwaq-timeline-line"><span/></div><div className="riwaq-timeline-content"><b>{e.students?.full_name||e.title}</b><span>{formatInTimeZone(e.starts_at,e.timezone)} · {e.title}{e.is_makeup?" · حصة تعويضية":""}</span></div><span className={`riwaq-status ${cls}`}>{label}</span></div>})}</div>:<div className="riwaq-empty"><CalendarDays size={28}/><h3>يوم هادئ</h3><p>لا توجد حصص قادمة.</p><Link className="riwaq-action-primary" href="/calendar-riwaq?action=new"><Plus size={15}/> إضافة موعد</Link></div>}</section>
  <section className="card riwaq-summary-card"><div className="riwaq-section-head"><div><span className="riwaq-section-kicker"><AlertTriangle size={14}/> يحتاج انتباهك</span><h2>التنبيهات</h2></div><Link className="riwaq-more" href="/notifications">كل التنبيهات</Link></div>{alerts.length?<div className="riwaq-summary-list">{alerts.slice(0,6).map((a,i)=><div key={i}><span>{a.kind==="payment"?<WalletCards size={14}/>:a.kind==="report"?<FileText size={14}/>:<AlertTriangle size={14}/>} {a.text}</span></div>)}</div>:<div className="riwaq-empty small"><CheckCircle2 size={28}/><h3>كل شيء تحت السيطرة</h3><p>لا توجد تنبيهات معلقة حاليًا.</p></div>}</section></div>
  <div className="riwaq-dashboard-grid lower"><section className="card riwaq-today-card"><div className="riwaq-section-head"><div><span className="riwaq-section-kicker"><CalendarDays size={14}/> جدول اليوم</span><h2>حصصك وأنشطتك</h2></div><Link className="riwaq-more" href="/calendar-riwaq">التقويم <ArrowLeft size={14}/></Link></div>{today.length?<div className="riwaq-timeline">{today.map(e=><div className="riwaq-timeline-item" key={e.id}><div className="riwaq-timeline-time">{formatTimeInZone(e.starts_at,e.timezone)}</div><div className="riwaq-timeline-line"><span/></div><div className="riwaq-timeline-content"><b>{e.students?.full_name||e.title}</b><span>{e.title} · {Math.round(hours(e)*60)} دقيقة</span></div><span className={`riwaq-status ${e.status==="completed"?"done":""}`}>{e.status==="completed"?"منتهية":"مجدولة"}</span></div>)}</div>:<div className="riwaq-empty small"><CalendarDays size={28}/><p>لا توجد حصص اليوم.</p></div>}</section>
  <section className="card riwaq-progress-card"><div className="riwaq-section-head"><div><span className="riwaq-section-kicker"><Clock3 size={14}/> التقدم</span><h2>ساعات الشهر</h2></div><span className="riwaq-progress-value">{Math.round(progress)}%</span></div><div className="riwaq-progress-ring"><div><b>{completed.toFixed(1)}</b><span>ساعة منفذة</span></div></div><div className="riwaq-meter"><span style={{width:`${progress}%`}}/></div><div className="riwaq-progress-meta"><span>منفذ: {completed.toFixed(1)}</span><span>مخطط: {planned.toFixed(1)}</span></div><Link className="riwaq-more" href="/hours">تفاصيل الساعات <ArrowLeft size={14}/></Link></section></div>
  <section className="card riwaq-students-card"><div className="riwaq-section-head"><div><span className="riwaq-section-kicker"><Users size={14}/> الطلاب</span><h2>الطلاب النشطون</h2></div><Link className="riwaq-more" href="/students">إدارة الطلاب <ArrowLeft size={14}/></Link></div><div className="riwaq-student-grid">{active.slice(0,8).map(s=><Link href={`/students/${s.id}`} className="riwaq-student" key={s.id}><div className="riwaq-avatar">{s.full_name?.trim()?.charAt(0)||"ط"}</div><div><b>{s.full_name}</b><span>{s.age?`${s.age} سنة`:"—"}</span></div><ArrowLeft size={14}/></Link>)}</div></section>
 </main></AppShell>;
}